### PR TITLE
fix: [Widget Image] Remove oldurl string check since it's always a string and prevent the ObjectURL cleaning resulting in a memory leak.

### PR DESCRIPTION
**Pull request by joseph2rs**
See #3170

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks!

This check was added in 1b1639118c1b8bde71e8691b5aa6e59887af9e4f (#1676) to distinguish between that src being an external url or an internal object url.

However, it looks like [step 2](https://w3c.github.io/FileAPI/#dfn-revokeObjectURL) of the revoking process checks to see if the url has scheme `blob:`, so I think we can call revoke on any URL (including external URLs) and it will silently return if the url is not a blob url.

I see that we have this same logic in the video and audio widgets. Can you fix it in those files too?

**Comment by jasongrout** [comment]
FYI, on current firefox and chrome, `URL.revokeObjectURL('http://google.com')` just silently returns without an error message, so I think we don't even have the error message the standard warns may happen.

**Comment by jasongrout** [comment]
Other places are at https://github.com/jupyter-widgets/ipywidgets/blob/1a121620aea08b2df4bcf92e851bd961317dc1db/packages/controls/src/widget_audio.ts#L65-L67 and https://github.com/jupyter-widgets/ipywidgets/blob/1a121620aea08b2df4bcf92e851bd961317dc1db/packages/controls/src/widget_video.ts#L68-L70

**Comment by joseph2rs** [comment]
FYI i removed also the check on `oldurl` since passing undefined or null fail silently.

**Comment by jasongrout** [comment]
> FYI i removed also the check on `oldurl` since passing undefined or null fail silently.

Reading the standard, we aren't guaranteed passing in undefined or null will always fail silently, just that a url that is not an object url will. In the standard, the first step is to parse the url, and the parsing standard seems to really want a string.

Can you put back in the oldurl test so we're following the standard more closely? That will make it more certain it will work across browsers, at least ones that implement the spec as written.

**Comment by jasongrout** [comment]
Thanks!

**Pull request merged**
