### PR TITLE
WIP Make ToggleButtons respect passed `style` kwarg

### PR DESCRIPTION
**Pull request by hinnefe2**
This PR is a (work in progress) attempt to solve #1691.

Things that ~~I've tried so far (which haven't worked)~~ this includes:

- [x] make `ToggleButtonStyle` inherit from `DescriptionStyle` in both the `.py` and `.ts` definitions.
- [x] modify the `styleProperties` in the `.ts` definition.

### CODE REVIEW

**Comment by jasongrout** [comment]
Ah, you'll also need to modify the styleProperties like the int slider: https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/controls/src/widget_int.ts#L59

**Comment by jasongrout** [comment]
To explain more: the error is here in the Travis log (which you can find by clicking on the "Details" link above, or on the red X:

```
lerna ERR! execute src/widget_selection.ts(370,7): error TS2417: Class static side 'typeof ToggleButtonsStyleModel' incorrectly extends base class static side 'typeof DescriptionStyleModel'.
lerna ERR! execute   Types of property 'styleProperties' are incompatible.
lerna ERR! execute     Type '{ button_width: { selector: string; attribute: string; default: any; }; }' is not assignable to type '{ description_width: { selector: string; attribute: string; default: any; }; }'.
lerna ERR! execute       Property 'description_width' is missing in type '{ button_width: { selector: string; attribute: string; default: any; }; }'.
```
The last line indicates that the styleProperties does not properly include a description_width value, which leads to the above suggestion to augment the styleProperties with the DescriptionStyleModel styleProperties.

Isn't typescript great? In normal javascript, we wouldn't have found out about this omission until we hit a probably hard-to-debug bug where the style properties wouldn't actually update. In this case, the typings force us to fix the bug before things even compile.

**Comment by jasongrout** [comment]
@hinnefe2 - thanks again for this PR. I should make a release tonight (i.e., in the next 10 hours or so) - please let me know if you have time to look at the above comment, or alternatively I can look into making the change.

**Comment by jasongrout** [comment]
Also, one more thing: the name/address on the commit is: "hinnefe2 <hhinnefeld@civisanalytics.com>". If you'd like your real name to show up in our changelog, can you either: 

(a) Tell git your name: `git config --global user.name "John Doe"`, OR
(b) add an entry to our `.mailmap` file which matches git commit information to current names/emails: https://github.com/jupyter-widgets/ipywidgets/blob/master/.mailmap (add a line that looks like:

```
Correct Name <correct email> hinnefe2 <hhinnefeld@civisanalytics.com>
```

**Comment by jasongrout** [comment]
(I could also make the release tomorrow morning, i.e., within 24 hours, if the extra time helps...)

**Comment by hinnefe2** [comment]
Hi @jasongrout - I think this is good to go. On my local machine the description widths for toggle buttons respect the `style` argument now.  

Thanks for helping me through this - java/typescript is a bit outside my wheelhouse but you made it easy to contribute. I'll definitely be back next time I find something that could use fixing.

**Comment by jasongrout** [comment]
Awesome, thanks!

**Comment by jasongrout** [comment]
This looks great to me too. I checked it and it works as well. Thanks again!

**Pull request merged**
