### PR TITLE
CONTRIBUTING.md did not have relevant info

### PR DESCRIPTION
**Pull request by CleoQc**
ref: https://github.com/jupyter-widgets/ipywidgets/issues/1827

Attempted to centralize all info related to how to become a contributor into one place

### CODE REVIEW

**Comment by CleoQc** [comment]
@jzf2101  Here it is.

**Comment by jzf2101** [comment]
@jasongrout I don't have the option to approve for some reason but this looks good to me

**Comment by jzf2101** [comment]
@CleoQc can you add also the comments from `dev_install.sh` to the documentation on prerequisities?

**Comment by jasongrout** [comment]
Thanks!

**Comment by jzf2101** [comment]
@jasongrout why aren't the changes showing up online?

**Comment by jasongrout** [comment]
(answered on gitter, but also here for completeness): you have to change the docs version to "latest" to see the changes on master.

**Pull request merged**
