### PR TITLE
[Backport 7.x] Use control comm target in LabManager

### PR DESCRIPTION
**Pull request by martinRenou**
Backport of #3335

### CODE REVIEW

**Comment by martinRenou** [comment]
Making it draft, I need to apply changes from #3335

**Comment by jasongrout** [comment]
@martinRenou said he plans to work on this this week for an upcoming 7.x minor release.

**Comment by martinRenou** [comment]
It's updated :)

**Comment by tkrabel-db** [comment]
@jasongrout @martinRenou I hope you don't mind if a stranger (at least for @martinRenou) asks questions in this thread :) I see that you have the notion of `_loadFromKernel` and `_loadFromKernelSlow`. I'm wondering: how slow is the old comm_info_request <> state update logic compared to the new one? Any numbers?

**Comment by martinRenou** [comment]
Hey @tkrabel-db :) We did some speed tests on the Voila implementation (which is exactly the one added in this PR), see https://github.com/voila-dashboards/voila/pull/766#issuecomment-925901034 and https://github.com/voila-dashboards/voila/pull/766#issuecomment-926418710.

**Comment by jasongrout-db** [comment]
@martinRenou - do you mind if we rename `_loadFromKernelSlow` to something that indicates the actual difference rather than the symptom? Perhaps `_loadFromKernelSeparate` or `_loadFromKernelModels` or something? I suppose we can rename `_loadFromKernel` to `_loadFromKernelControl` or `_loadFromKernelWidgetManager` or something to make the distinction even clearer.

As we've talked about before, it may be that `_loadFromKernel` ends up with a websocket message that is too big and gets dropped, in which case `_loadFromKernelSlow` is actually faster :).

**Comment by martinRenou** [comment]
Thanks!

**Comment by jasongrout** [comment]
@martinRenou looked at these last changes: https://gitter.im/jupyter-widgets/Lobby?at=62062b2803f27047822cde0c

**Comment by ibdafna** [comment]
@meeseeksdev please backport to master

**Pull request merged**
