### PR TITLE
More docs updates

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- follow-up on #3673 
  - thanks @jtpio re piplite path https://github.com/jupyter-widgets/ipywidgets/pull/3673#discussion_r1084660125

## Changes

- [x] fix jupyterlite wheel paths
- [x] update branch references: `master` -> `main`
- [x] try to fix binder workflow (haven't seen it re-run yet, because it only fires on `pull_request_opened`)
- [x] look at some more sphinx warnings
- [x] restore full index sidebar
- [x] rework demo links (less bs (ha!))

### CODE REVIEW

**Comment by bollwyvl** [comment]
Modulo not knowing if this will fix the binder badge workflow,  this is ready for review (and :jack_o_lantern: merge is again fine).

**Comment by agoose77** [comment]
These changes are all fantastic.

Minor points:

- For me, the button icons are misaligned
image
- Personally I prefer `API Reference` to `Reference`
- I'd be tempted to move the try buttons to the index page only, maybe as a card?
- On Awkward Array, we have a quick-links card that might be similarly useful (maybe without the badges for ipywidgets) https://awkward-array.org/doc/main/

**Comment by bollwyvl** [comment]
> button icons are misaligned

the first two are actually radios, was trying to "act like a local" and use bootstrap sugar. I'll try a treatment without.

>  move the try buttons to the index page only,

Could move to the bottom. Actually, it would be lovely to have a sidebar that was "open in lite," next to "edit in github".

> API Reference to Reference

I'm just working off the upstream language guidance. There might be things there _other_ than the API at some point, though can't tell what those would be.

**Comment by bollwyvl** [comment]
image

**Comment by agoose77** [comment]
> image

Much better!!

**Comment by jasongrout** [comment]
Thanks!

**Comment by bollwyvl** [comment]
Cool. I think that's all the high-value stuff that wouldn't require a new release of something.

**Comment by jasongrout** [comment]
> Cool. I think that's all the high-value stuff that wouldn't require a new release of something.

Thanks again for the massive amount of overhauling you did!

**Pull request merged**
