### PR TITLE
Switch to Jupyter alabaster theme

### PR DESCRIPTION
**Pull request by jasongrout**
Also add the asynchronous notebook to the index, and update the doc requirements.

### CODE REVIEW

**Comment by blink1073** [comment]
Heads up before you merge this: https://github.com/jupyterlab/jupyterlab/pull/2240

**Comment by blink1073** [comment]
I'd suggest adding something like this to your travis script: https://github.com/jupyterlab/jupyterlab/blob/875eb8b5f54e2e73fdc767100eb7917c5f69eb1f/scripts/travis_script.sh#L52-L58

**Comment by jasongrout** [comment]
Thanks!

**Comment by jasongrout** [comment]
@blink1073 - I'm not seeing a conflict between recommonmark and sphinx 1.6: https://travis-ci.org/jupyter-widgets/ipywidgets/jobs/233787986#L436

**Comment by blink1073** [comment]
That's a head scratcher.

**Pull request merged**
