### PR TITLE
Upgrade webpack

### PR DESCRIPTION
**Pull request by jasongrout**
This upgrades webpack and the webpack loaders. It is a work in progress, and it builds on #3162.

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks!

Thinking that we might want to cut a new alpha release when this one gets in, which would also include the TypeScript update from https://github.com/jupyter-widgets/ipywidgets/pull/3162

**Comment by jtpio** [comment]
Just rebased on the latest `master`.

**Comment by jasongrout** [comment]
I'd like to do one more round of upgrades of other packages before releasing another alpha, to get us basically set to latest versions of everything.

**Comment by jasongrout** [comment]
Sorry, I accidentally didn't pull down the rebase before force-pushing a fix to a commit. I've now rebased on master as well.

**Comment by jasongrout** [comment]
Almost all tests have passed - setting to ready for review.

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
