### PR TITLE
Change media widgets to use memory views.

### PR DESCRIPTION
**Pull request by jasongrout**
This can be more efficient with fewer copies in some cases, such as uploading a file and setting the value from the file content. Also, the deserialization does not involve a copy anymore.

CC @pbugnion, @maartenbreddels

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
We should check the impact of this on ipywebrtc.

**Comment by pbugnion** [comment]
As part of the work on this, we should change the docs for the file upload widget to avoid an unnecessary `.tobytes()` when embedding the uploaded content in an image widget (x-ref #2722).

**Comment by jasongrout** [comment]
> We should check the impact of this on ipywebrtc.

@maartenbreddels - are you able to do this?

**Comment by jasongrout** [comment]
> We should check the impact of this on ipywebrtc.

It may be easiest to do this with an alpha release of ipywidgets with this merged in? Can we merge this in, and revert later if there are problems?

**Comment by jasongrout** [comment]
Merging - if it is an issue, especially with ipywebrtc or some other downstream library, we can revert.

**Pull request merged**
