### PR TITLE
Use window.requirejs instead of window.require which is overriden by the RTD theme

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by vidartf** [comment]
So, this should mean we don't need [this helper script](https://github.com/jupyter-widgets/widget-ts-cookiecutter/blob/ed554d3955b8dbc311f0964078b3df5208f111f0/%7B%7Bcookiecutter.github_project_name%7D%7D/docs/source/_static/helper.js) for widget docs, right?

**Comment by vidartf** [comment]
Also, for inter-linking: https://github.com/rtfd/sphinx_rtd_theme/issues/497

**Comment by maartenbreddels** [comment]
Was wondering about that too. @vidartf this issue only showed up using the the rtd theme locally right?

**Comment by vidartf** [comment]
@maartenbreddels yes

**Comment by SylvainCorlay** [comment]
Right, I did not know about this helper.

**Comment by vidartf** [comment]
Temporary workaround together with the code in doc config.

**Pull request merged**
