### PR TITLE
for notebook 5.3 you don't need to enable the extensions anymore, solves #1908

### PR DESCRIPTION
**Pull request by maartenbreddels**
for notebook 5.3 you don't need to enable the extensions anymore, solves #1908

### CODE REVIEW

**Comment by jasongrout** [comment]
For backwards compatibility, it's actually:

```
{
  "load_extensions": {
    "jupyter-js-widgets/extension": true
  }
}
```

**Comment by maartenbreddels** [comment]
good catch 👍

**Comment by jasongrout** [comment]
Thanks. Came from trying it out and seeing it didn't work :).

**Comment by maartenbreddels** [comment]
After the third widget I got a bit overconfident :)

**Comment by jasongrout** [comment]
There be dragons in this ancient codebase!

**Comment by jasongrout** [comment]
This works great. Thanks!

**Pull request merged**
