### PR TITLE
Drop support for legacy Python 2.7 and EOL 3.4

### PR DESCRIPTION
**Pull request by hugovk**
For #2554.

Also, Python 3.4 is EOL and no longer receiving security updates (or any updates) from the core Python team.

Version | Release date | Supported until
--- | ---------- | ----------
2.7 | 2010-07-03 | 2020-01-01
3.4 | 2014-03-16 | 2019-03-16

Source: https://en.wikipedia.org/wiki/CPython#Version_history

### CODE REVIEW

**Comment by jasongrout** [comment]
Thank you!

**Comment by jasongrout** [comment]
This looks great, and some hand-testing indicates it works great too. Thanks again!

**Comment by hugovk** [comment]
You're welcome! Happy New year!

**Comment by maartenbreddels** [comment]
:+1:

(from mobile phone)

**Pull request merged**
