### PR TITLE
Use `dict` instead of `print` to test callable without signature

### LINKED ISSUE #3459: One test fails with Python 3.11 beta 1
We are building RPM packges in Fedora with the latest Python 3.11 beta 1 nad ipywidgets fails:

```
=================================== FAILURES ===================================
___________________________ test_interact_noinspect ____________________________

    def test_interact_noinspect():
        a = u'hello'
>       c = interactive(print, a=a)

ipywidgets/widgets/tests/test_interaction.py:706: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ipywidgets/widgets/interaction.py:201: in __init__
    self.kwargs_widgets = self.widgets_from_abbreviations(new_kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = interactive(_dom_classes=('widget-interact',))
seq = [('sep', ' ', ' '), ('end', '\n', '\n'), ('file', None, None), ('flush', False, False)]

    def widgets_from_abbreviations(self, seq):
        """Given a sequence of (name, abbrev, default) tuples, return a sequence of Widgets."""
        result = []
        for name, abbrev, default in seq:
            widget = self.widget_from_abbrev(abbrev, default)
            if not (isinstance(widget, ValueWidget) or isinstance(widget, fixed)):
                if widget is None:
>                   raise ValueError("{!r} cannot be transformed to a widget".format(abbrev))
E                   ValueError: None cannot be transformed to a widget

ipywidgets/widgets/interaction.py:301: ValueError
```

### PR DESCRIPTION
**Pull request by frenzymadness**
In Python 3.11, `inspect.signature(print)` no longer raises
ValueError.

Fixes: https://github.com/jupyter-widgets/ipywidgets/issues/3459

### CODE REVIEW

**Comment by frenzymadness** [comment]
Would it make sense to add Python 3.11 to the CI?

**Comment by jasongrout** [comment]
> Would it make sense to add Python 3.11 to the CI?

Sure. Would you mind adding it to https://github.com/jupyter-widgets/ipywidgets/blob/474bbc99f2a62ce23fc9e4d681f9a78a27b31b87/.github/workflows/tests.yml#L91 ?

From https://til.simonwillison.net/github-actions/python-3-11, it seems that just adding `"3.11-dev"` may be all that is needed.

**Comment by jasongrout** [comment]
> it seems that just adding `"3.11-dev"` may be all that is needed.

Yes, `"3.11-dev"` according to the [docs](https://github.com/actions/setup-python#available-versions-of-python): 

> Use -dev instead of a patch number (e.g., 3.11-dev) to install the latest patch version release for a given minor version, alpha and beta releases included.

We might need to also update https://github.com/jupyter-widgets/ipywidgets/blob/474bbc99f2a62ce23fc9e4d681f9a78a27b31b87/.github/workflows/tests.yml#L96 to version 2: `actions/setup-python@v2`

**Comment by frenzymadness** [comment]
Should I open a new PR? I can also add it here as both changes are related to Python 3.11.

**Comment by jasongrout** [comment]
> Should I open a new PR? I can also add it here as both changes are related to Python 3.11.

I think adding it here makes a lot of sense. And if you add it here, we'll get to see that your change makes tests pass for Python 3.11 too. Thanks!

**Comment by jasongrout** [comment]
Awesome, thank you!

**Comment by jasongrout** [comment]
@meeseeksdev please backport to 7.x

**Comment by jasongrout** [comment]
Backported in #3480

**Pull request merged**
