### PR TITLE
Kernel is the source of truth: support multiple clients and fixes out of sync bug

### LINKED ISSUE #3111: Widget out of sync: fundamental issue?
# Code 
```python
import ipywidgets as widgets
import time

text = widgets.Text(value="...", continuous_update=False)
def on_change(change):
    if text.value == "sleep":
        time.sleep(6)
        text.value = "I computed for 6 seconds"
text.observe(on_change, "value")
text
```

# Demo
sync-bug

# What happens?
If we enter 'sleep', an update event is send to the kernel, which takes 6 seconds to finish. Before it finishes, we change the text to `"bug?"`, which is queued at the kernel, because the `time.sleep(6)` is still ongoing. Next, we send an update event from the kernel to the frontend, changing the Text value to `"I computed for 6 seconds"`, after which we process the queued message from the frontend which changes the kernel side value to `"bug?"`.

Now the frontend thinks the value is `"I computed for 6 seconds"` while the kernel thinks it is `"bug?"`

# What I think should happen
There must be a ton of literature written about keeping two systems in sync, but I think there should be an agreement of which side holds the ultimate source of truth. Since ipywidgets is mainly about programming from the kernel, I think that should be the kernel by default, and therefore I think the kernel should by default echo back the value to the frontend.

In this case, the `"bug?"` update message should be sent back to the frontend. The reason we don't do that, is that we implicitly assume the message (update to `"bug?"`) was generated AFTER the change to `"I computed for 6 seconds"` and therefore we assume that the frontend also has that value.

There are situations, like in ipywebrtc where the 'source of truth' is the frontend, since it generates the data (video stream), so there should be an opt-out way of echoing back changes.

# Context

This bug/feature was discovered by @mariobuikhuizen while trying to solve an infinite echo problem: https://github.com/spacetelescope/jdaviz/issues/185 🤷

### PR DESCRIPTION
**Pull request by maartenbreddels**
As described in #3111 it can happen that a frontend can get out of sync
due to not echoing back messages from the frontend.

Widgets can opt out of this behaviour if it is too costly and/or does
not make sense, e.g. the data from the file widget.

Fixes #3111

### CODE REVIEW

**Comment by jasongrout** [comment]
In our dev meeting today, we were discussing this, and whether it should be a target for 8.0, or whether it should be tackled in the (hopefully upcoming) explorations in moving the syncing to a real-time collaboration backend.

**Comment by jasongrout** [comment]
We propose moving this to 9.0 with the (hopefully upcoming) move to an RTC framework for syncing data. Maarten, what do you think?

**Comment by jasongrout** [comment]
Moving to Future (e.g., 9.0) since there was no follow-up. Maarten, if you'd like to discuss this more, please comment. We can always move it back if that's what everyone decides.

**Comment by maartenbreddels** [comment]
I think that makes sense!

**Comment by SylvainCorlay** [comment]
This poses an issue in the following situation:

 - A client moves continuously a slider from left to right
 - It gets the echos back from past positions of the handles, making the handle jump to lesser values of the slider.

We have seen this bug make slider handles jitter.

**Review by SylvainCorlay — CHANGES_REQUESTED** [review]
As per my last comment.

**Comment by maartenbreddels** [comment]
We can see this from the parent header, if we get an update from the kernel, where the parent header `msg_id` **equals** the last msg_id of the update we send to the kernel, (*and* our value has changed, but that is something backbone should figure out), we should update our back model model. If the `msg_id` is **not equal** to our last update message (on a per property/trait basis), it's an old message, and we can ignore it.

**Comment by maartenbreddels** [comment]
on the client that is changing the slider, there is not jitter at all, actually I also fixed an old but I think that caused more jitter that needed since we set the state of a property, even though it was already planned for sending to the kernel (attr present in _msg_buffer)
widgets-magic4

**Comment by maartenbreddels** [comment]
with the env var `JUPYTER_WIDGETS_ECHO=0` the echo can be turned off, of simply from the Python module.

**Comment by maartenbreddels** [comment]
We quickly realised with the proposed change, we cannot control from the kernel to fall back to the old behaviour. Therefore we modified the update msg from the kernel to the frontend to contain a list of properties that are echoed back.

This makes it that debugging is easier, it's clear from the message what is going on, and the kernel determines the new behaviour or the old.

Mario tested this with STScI's jdaviz, and this works really well, we see no jitter, and we can can connect multiple clients.

The new behaviour can be destribed as follows:
 * The kernel can decide to send back (echo) updates to the frontend, and if so, will let the frontend know via the 'echo' list of properties in the update message. The kernel side can opt out of echo messages globally via the `JUPYTER_WIDGETS_ECHO` variable/env_var (application setting, like voila), or on a trait basis via the `no_echo` metadata.
 * A frontend can choose to ignore updates which are echos until it has received the echo of the last update it send.

On top of that, we also ignore updates in the frontend for which we are about the send out an update message (i.e. the attribute is in `this._msg_buffer`).

There was one scenario I was worried about, so I decided to describe it:
When two clients are connected, client 1 sends an update for `value=1`, and client 2 sends an update for `value=42` at the same time (so they are both in flight), there are two situations possible:
 * Situation 1:
   * The kernel first sends an echo for `value=1` 
   * client 1 received its update, and will take any update afterwards (`value=1`)
   * client 2 ignores this update with echo (because it did not see it's own update yet) (`value=42`)
   * The kernel sends an echo for `value=42`
   * client 1 accepts any update (`value=42`)
   * client 2 received its update, and will take any update afterwards (`value=42`)
  * Situation 2:
    * The kernel fist sends an echo for `value=42` 
    * client 1 ignores this update with echo (because it did not see it's own update yet) (`value=1`)
    * client 2 received its update, and will take any update afterwards (`value=42`)
    * The kernel sends an echo for `value=1`
    * client 1 received its update, and will take any update afterwards (`value=1`)
    * client 2 accepts any update (`value=1`)


In both cases, the clients end up in the same state, and it's the kernel that determines the final state. I think with `JUPYTER_WIDGETS_ECHO=1` we can now also really say that the kernel is the 'source of truth', which makes sense in a 1-to-n topology.

**Comment by maartenbreddels** [comment]
Just to clarify, this PR originally was to fix #3111 but the fix 'coincidentally' also allows for multiple clients, which means it fixes #1218

Related are:
 * https://github.com/voila-dashboards/voila/issues/515
 * https://github.com/voila-dashboards/voila/issues/95
 * #2628 
 * https://github.com/matplotlib/ipympl/issues/328
 * https://github.com/jupyter/jupyter_client/issues/263
 * https://github.com/jupyter-widgets/ipywidgets/issues/1881

**Comment by maartenbreddels** [comment]
thanks to @mariobuikhuizen for doing the last work on having old and new behaviour.

Note that the code is a bit 'funny', where the new behaviour is under an if condition, ending in a return statement. The reason is to keep the diff as small, so it's easy to see that the old behaviour is not modified. Over time I've learned to appreciate clear git logs more. In the future, we can easily take out the old behaviour, and clean up the code.

**Review by jasongrout — CHANGES_REQUESTED** [review]
This protocol change should be documented in https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/schema/messages.md#widget-messaging-protocol-version-2. Since it is backwards compatible, perhaps we bump the protocol version to 2.1?

**Comment by maartenbreddels** [comment]
Note from @jasongrout:
If we get an update from the frontend, but that trait is marked 'no_echo', we do send it back to the frontend in the 'echo' list, but it does not get the updated value. The frontend code currently handles this, and it's informative, but we should maybe explicitly state this.

**Comment by SylvainCorlay** [comment]
@maartenbreddels @jasongrout @ibdafna was there a final decision to go ahead and merge after I left the call?

**Review by vidartf — APPROVED** [review]
I haven't tested running of the code, but AFAICT this code now meets all the targets we said we needed for including this in the RC

**Comment by vidartf** [comment]
On things that were not a prerequisite for inclusion in the RC, but I would consider a prerequisite for release the final version with this on as the default: I think that we should make sure we have tests that properly cover the cases where the previous property lock prevented flickering of values to occur. I'm uncertain if the new code properly handles all of the corner cases there, and more regression tests would go a long way in acting as a proof of that.

**Comment by ibdafna** [comment]
@SylvainCorlay I believe we agreed to merge, release a new *beta* tomorrow, and for @maartenbreddels to add documentation about the changes this PR introduces, before releasing a new RC in the new year.

**Comment by SylvainCorlay** [comment]
> On things that were not a prerequisite for inclusion in the RC, but I would consider a prerequisite for release the final version with this on as the default: I think that we should make sure we have tests that properly cover the cases where the previous property lock prevented flickering of values to occur. I'm uncertain if the new code properly handles all of the corner cases there, and more regression tests would go a long way in acting as a proof of that

Yes, we spent an hour this morning trying to break it, both by inspecting the code and trying different scenarios.

**Review by SylvainCorlay — APPROVED** [review]

**Comment by SylvainCorlay** [comment]
Merged!

**Comment by jasongrout** [comment]
I thought we had decided to document this in the widget protocol (i.e., https://github.com/jupyter-widgets/ipywidgets/pull/3195#pullrequestreview-838328944), then merge. I do think it is important to document this before releasing a release with it, since it is big enough change (especially with default on).

**Comment by jasongrout** [comment]
I've opened https://github.com/jupyter-widgets/ipywidgets/issues/3330 to track the documentation and protocol version changes.

**Comment by ibdafna** [comment]
@jasongrout apologies for the mixup. @maartenbreddels will wait for a PR with documentation changes before releasing

**Comment by jasongrout** [comment]
No problem. We could also just cut the beta from just before the merge commit.

**Comment by ibdafna** [comment]
@jasongrout will do that!

**Pull request merged**
