### PR TITLE
Update flex-grow example

### PR DESCRIPTION
**Pull request by DougRzz**
Flex grow example has been corrected.  Unfortunately I don't know how to embed the widgets so they are rendered in Github.

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks!

Do you think you might be able to just make changes to the inputs, and either don't change outputs or clear the outputs, so the diffs just contain the changes to the code? This is one of the problems we suffer from having notebooks as docs.

If it's hard for you to do that, then I can try taking these changes and cutting them down to just the changes in the inputs.

**Comment by jasongrout** [comment]
I think this is the actual diff of the code - does this look right?

```patch
--- Widget Styling.ipynb	2018-03-20 00:11:21.000000000 -0700
+++ wstylenew.ipynb	2018-03-20 00:09:42.000000000 -0700
@@ -397,8 +397,7 @@
    "source": [
     "from ipywidgets import Layout, Button, Box\n",
     "\n",
-    "items_layout = Layout(flex='1 1 auto',\n",
-    "                      width='auto')     # override the default width of the button to 'auto' to let the button grow\n",
+    "items_layout = Layout( width='auto')     # override the default width of the button to 'auto' to let the button grow\n",
     "\n",
     "box_layout = Layout(display='flex',\n",
     "                    flex_flow='column', \n",
@@ -407,7 +406,7 @@
     "                    width='50%')\n",
     "\n",
     "words = ['correct', 'horse', 'battery', 'staple']\n",
-    "items = [Button(description=w, layout=items_layout, button_style='danger') for w in words]\n",
+    "items = [Button(description=word, layout=items_layout, button_style='danger') for word in words]\n",
     "box = Box(children=items, layout=box_layout)\n",
     "box"
    ]
@@ -425,21 +424,28 @@
    "metadata": {},
    "outputs": [],
    "source": [
-    "from ipywidgets import Layout, Button, Box\n",
+    "from ipywidgets import Layout, Button, Box, VBox\n",
     "\n",
-    "items = [\n",
-    "    Button(description='weight=1'),\n",
-    "    Button(description='weight=2', layout=Layout(flex='2 1 auto', width='auto')),\n",
-    "    Button(description='weight=1'),\n",
+    "# Items flex proportionallly to the weight and the left over space around the text \n",
+    "items_auto = [\n",
+    "    Button(description='weight=1, auto', layout=Layout(flex='1 1 auto', width='auto'), button_style='danger'),\n",
+    "    Button(description='weight=3, auto', layout=Layout(flex='3 1 auto', width='auto'), button_style='danger'),\n",
+    "    Button(description='weight=1, auto', layout=Layout(flex='1 1 auto', width='auto'), button_style='danger'),\n",
     " ]\n",
     "\n",
+    "# Items flex proportionallly to the weight \n",
+    "items_0 = [\n",
+    "    Button(description='weight=1, _0%', layout=Layout(flex='1 1 0%', width='auto'), button_style='danger'),\n",
+    "    Button(description='weight=3, _0%', layout=Layout(flex='3 1 0%', width='auto'), button_style='danger'),\n",
+    "    Button(description='weight=1, _0%', layout=Layout(flex='1 1 0%', width='auto'), button_style='danger'),\n",
+    " ]\n",
     "box_layout = Layout(display='flex',\n",
     "                    flex_flow='row', \n",
     "                    align_items='stretch', \n",
-    "                    border='solid',\n",
-    "                    width='50%')\n",
-    "box = Box(children=items, layout=box_layout)\n",
-    "box"
+    "                    width='70%')\n",
+    "box_auto = Box(children=items_auto, layout=box_layout)\n",
+    "box_0 = Box(children=items_0, layout=box_layout)\n",
+    "VBox([box_auto, box_0])"
    ]
   },
   {
@@ -506,7 +512,7 @@
     "                    border='3px solid black',\n",
     "                    width='500px',\n",
     "                    height='',\n",
-    "                    flex_direction='row',\n",
+    "                    flex_flow='row',\n",
     "                    display='flex')\n",
     "carousel = Box(children=items, layout=box_layout)\n",
     "VBox([Label('Scroll horizontally:'), carousel])"
```

**Comment by DougRzz** [comment]
@jasongrout  Yes.  That is correct.

**Comment by jasongrout** [comment]
Okay, I'm going to make just the changes to just the input text of the notebook (hopefully in your name) and push it here. When we do the actual release, we'll rerun the notebook so that we don't have a lot of churn of output.

**Comment by jasongrout** [comment]
In order to make sure you receive credit for this commit, could you make replace the above commits with the diff above? For convenience, I made it a gist, so you just have to do this from the current git master:

```
curl https://gist.githubusercontent.com/jasongrout/734ebc3b22ef45d2afce76fa842ca29b/raw/0261290ffdb4857d272bf4f6781988eae7fa03c8/styling.patch | git apply
```

**Comment by jasongrout** [comment]
(Or if you don't care about getting credit for the commit or if it's too much of a hassle, I can just commit it and give you credit in the commit message)

**Comment by DougRzz** [comment]
Thanks for finding a way for me to get credit for this.   I can't load Github desktop on my work computer   (we use MS VSTS!) but I can try your gist later tonight from my home laptop.   If you would like to commit this soon (I notice you are wanting to release v7.2 and are cleaning up the PRs), I am also totally fine with you doing the commit yourself.

**Comment by jasongrout** [comment]
> If you would like to commit this soon (I notice you are wanting to release v7.2 and are cleaning up the PRs), I am also totally fine with you doing the commit yourself.

We can wait - we have a few other PRs in progress.

**Comment by jasongrout** [comment]
Thanks! Can you overwrite your previous commits - the point here is to avoid the huge churn in the notebooks in your earlier commits? Perhaps something like:

```
git reset --hard c2618f43abe30812176004b6c122e7a8e9cca567
```
This command resets your git to point to the commit just before this PR, *then* do the git curl | apply thing.

**Comment by jasongrout** [comment]
(Or if you're familiar with git rebase, you can rebase and get rid of the commits earlier...)

**Comment by DougRzz** [comment]
@jasongrout Thanks for the suggestions but I can't get many of the git commands to work.  I need to find a spare day to learn git.

**Comment by jasongrout** [comment]
I can see if I can do it too.

**Comment by jasongrout** [comment]
@DougRzz - how is https://github.com/jupyter-widgets/ipywidgets/pull/2010?

**Comment by jasongrout** [comment]
Also, I noticed that the name in your commit is just "DougRzz". We typically put full names in our release notes. If you'd like your full name in our release notes, I can change the commit to contain it if you mention it here, or we can add an entry to the .mailmap file at https://github.com/jupyter-widgets/ipywidgets/blob/master/.mailmap. If you don't want your full name in the release notes, that's fine too - you'll just show up as DougRzz.

**Comment by jasongrout** [comment]
(to update your git commits with your full name, see https://help.github.com/articles/setting-your-username-in-git/)

**Comment by jasongrout** [comment]
I stripped things down to just the code changes in #2010 and merged that. @DougRzz - please us know if there is anything in here that didn't make it into #2010.

**Pull request closed without merging**
