### PR TITLE
Bump controls version to 1.2.0

### PR DESCRIPTION
**Pull request by jasongrout**
We do this now so we can test the backwards compatibility before the release.

### CODE REVIEW

**Comment by jasongrout** [comment]
I just changed the logic of the JupyterLab manager - if a specific module *version* is requested (not a semver range), then it defaults to the `^` semver range to get a compatible module.

This would fix the problem we see in #2006, for example. If someone wants to insist on a specific version, they should use the range specifier `=1.2.3`.

@SylvainCorlay - thoughts? This does change the behavior for plain versions, but I think it makes the behavior more intuitive and better addresses the various places we need version numbers. I think it also probably makes sense to make the same change in the html manager?

**Comment by jasongrout** [comment]
ping @SylvainCorlay

**Comment by vidartf** [comment]
For future reference it would be nice if this had some tests outlining basic expected behavior. A side effect of this is that it is impossible for packages to lock one version to another (or that would require a one-element range).

**Comment by jasongrout** [comment]
> A side effect of this is that it is impossible for packages to lock one version to another (or that would require a one-element range).

Yes, it would require a semver range `=1.2.3`

**Comment by jasongrout** [comment]
(If this is too big of a change for a minor release, we can probably hold off on something like this until 8.0)

**Comment by jasongrout** [comment]
> (If this is too big of a change for a minor release, we can probably hold off on something like this until 8.0)

Since this *is* technically a backwards-incompatible change in general, I special-cased the changes to just the Jupyter-widgets/[base,controls] packages. We can take up the issue of making the more general change for 8.0 later.

**Comment by jasongrout** [comment]
> For future reference it would be nice if this had some tests outlining basic expected behavior. A side effect of this is that it is impossible for packages to lock one version to another (or that would require a one-element range).

The last commits roll back the behavior for general packages.

**Comment by nscozzaro** [comment]
I'm trying to get ipywidgets to work in my JupyterLab extension but I'm getting an error related to this, which I don't understand: "Error: Module @jupyter-widgets/base, semver range ^1.2.0 is not registered as a widget module", and many other similar errors. 

What I did was to copy all of the code from the jupyterlab-manager extension into my extension, changed the INotebookTracker to my modified INotebookTracker, and now I'm getting this error. Would very much appreciate any guidance as to how I might solve this problem. Thanks


image

image

**Pull request merged**
