### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by MicaelJarniac**
Related to #3061

### CODE REVIEW

**Comment by MicaelJarniac** [comment]
I managed to fix one of the broken links, not sure about the other ones yet.

**Comment by MicaelJarniac** [comment]
The other broken link seems to be related to #2677. The file it links to has been deleted on that pull request.

**Comment by MicaelJarniac** [comment]
There's a replacement for `Widget Custom.ipynb` being worked on in #2919. The specific anchor may not match exactly, however.

**Comment by jtpio** [comment]
Thanks for catching this!

**Comment by jasongrout** [comment]
Thanks!

**Pull request merged**
