### PR TITLE
Add a workflow to test the packaging

### PR DESCRIPTION
**Pull request by jtpio**
Follow-up to #3119 

This adds a new workflow on CI to test installing `ipywidgets` and `jupyterlab_widgets` with the whell and the sdist.

This can help check the extensions are correctly bundled and installed.

### CODE REVIEW

**Comment by jasongrout** [comment]
It seems the matrix was not actually working the way we thought - the dist was overwriting itself, instead of adding more possibilities. I think I fixed it...

**Comment by jasongrout** [comment]
@jtpio - I think this is good now. I've added a bunch to the PR, so it would be great if you could look over it again. If it looks good to you, then +1 from me if you want to merge it.

**Review by jasongrout — APPROVED** [review]

**Comment by jasongrout** [comment]
Summary of changes:

- made sure that the ipywidgets wheel and sdist, as well as widgetsnbextension and jupyterlab_widgets sdists were tested
- Streamlined to just windows and linux, python 3.9, except we also test the ipywidgets sdist on python 3.6 windows and linux. I figured the macOS was similar enough to the linux we didn't need to test that as well.
- Added caching for the installs

**Comment by jtpio** [comment]
Thanks Jason, looks good!

**Pull request merged**
