### PR TITLE
Checkbox, RadioButton, and spacing functionality/ux improvements

### PR DESCRIPTION
**Pull request by maxnoy**
- Checkbox description on the right
- Checkbox indent
- Improved spacing between description and widgets
- Reduce spacing between radio buttons

### CODE REVIEW

**Comment by maxnoy** [comment]
Changes:
- Checkbox descriptions are clickable and on the right
- Reduced spacing between radiobutton options
- RadioButton widget autosizes to a multiple of single-line widgets to still line up properly
- Doubled margin between descriptions and widgets
- Checkboxes and RadioButtons are now aligned properly vertically with other widget controls
- RadioButton widget fix for when options are reset to empty list

**Comment by maxnoy** [comment]
**Before** 
ipw1-before 

**After**
ipw1-after

**After -- showing horizontal alignment**
ipw1-afteraligned

**Comment by jasongrout** [comment]
Do you think this is ready to review/merge?

**Comment by jasongrout** [comment]
Also, this fixes #237.

**Comment by maxnoy** [comment]
@jasongrout, I believe so.

**Comment by jasongrout** [comment]
Awesome! I won't be able to look at this again until Monday - @maartenbreddels or @SylvainCorlay, feel free to review and merge this before then if you want. Otherwise I'll take it back up Monday.

Thanks @maxnoy! It looks and functions way, way better.

**Comment by maxnoy** [comment]
Thank you again @jasongrout!!

**Comment by jasongrout** [comment]
Tested this out, and it seems to work great. Thanks!

**Comment by maxnoy** [comment]
Thanks @jasongrout!!

**Pull request merged**
