### PR TITLE
Fix setting a selection index when having duplicate values

### LINKED ISSUE #2513: RadioButton with options having the same value
```python
import ipywidgets as widgets
# widgets.__version__ == 7.2.1

colors = [["red",1], ["blue",2] ,["green",3], ["yellow",2]]
blob = widgets.RadioButtons(options=colors)
blob
```
For example selecting "yellow", it will automatically change the selected option to "blue". It picks the lowest indexed option with the same value. To actually select "yellow" a second click is needed.

Is this the intended behavior? If not, it would be real neat if options with different labels and the same values was supported.

### PR DESCRIPTION
**Pull request by jasongrout**
Fixes #2513 

Basically, when changing a selection that had duplicate values or labels, we always ended up resetting the index to the first such value or label. Now we check to see if the current index is the correct label/value before we reset the index.

I added a test which fails before the fix and passes after the fix.

### CODE REVIEW

**Comment by jasongrout** [comment]
CC @maartenbreddels @bbettss

**Comment by bbettss** [comment]
Awesome, thank you!

**Comment by jasongrout** [comment]
Thanks for pointing out the issue with a very clear reproducible code snippet!

**Comment by maartenbreddels** [comment]
Awesome, LGTM!

**Comment by jasongrout** [comment]
Feel free to merge @maartenbreddels :)

**Pull request merged**
