### PR TITLE
WIP: Document of the attributes for each model

### PR DESCRIPTION
**Pull request by jasongrout**
This is work towards fixing #1032 and #790.

CC @rgbkrk

### CODE REVIEW

**Comment by rgbkrk** [comment]
Great!

**Comment by jasongrout** [comment]
I also moved the messaging protocol description here, to start working on #790 as well.

**Comment by jasongrout** [comment]
I split out the message protocol documentation to https://github.com/ipython/ipywidgets/pull/1215

**Comment by jasongrout** [comment]
@SylvainCorlay - travis seems to work now here...

**Comment by jasongrout** [comment]
I think this is good enough for now - we can iterate on this later.

**Pull request merged**
