### PR TITLE
Add a variable-length tuple type and use it to enhance type checking.

### LINKED ISSUE #1960: trying to add figures to Tab widget - ValueError: Can't clean for JSON: <matplotlib.figure.Figure
Using ipywidgets with `%matplotlib notebook` in jupyter notebook.

I'm getting this error after adding few figures `fig` to `children` list:

```
for i, aw in enumerate(af):
  fig = plt.figure()
  plotw(aw, plt.gca())
  children.append(fig)

tab = widgets.Tab()
tab.children = children
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-62-e555be3f4d7a> in <module>()
     16         #    afield, akey, avalue)))
     17     tab = widgets.Tab()
---> 18     tab.children = children
     19     for i, aw in enumerate(af):
     20         tab.set_title(i, aw)

C:\Python\Python36_64b\lib\site-packages\traitlets\traitlets.py in __set__(self, obj, value)
    583             raise TraitError('The "%s" trait is read-only.' % self.name)
    584         else:
--> 585             self.set(obj, value)
    586 
    587     def _validate(self, obj, value):

C:\Python\Python36_64b\lib\site-packages\traitlets\traitlets.py in set(self, obj, value)
    572             # we explicitly compare silent to True just in case the equality
    573             # comparison above returns something other than True/False
--> 574             obj._notify_trait(self.name, old_value, new_value)
    575 
    576     def __set__(self, obj, value):

C:\Python\Python36_64b\lib\site-packages\traitlets\traitlets.py in _notify_trait(self, name, old_value, new_value)
   1137             new=new_value,
   1138             owner=self,
-> 1139             type='change',
   1140         ))
   1141 

C:\Python\Python36_64b\lib\site-packages\ipywidgets\widgets\widget.py in notify_change(self, change)
    595             if name in self.keys and self._should_send_property(name, change['new']):
    596                 # Send new state to front-end
--> 597                 self.send_state(key=name)
    598         super(Widget, self).notify_change(change)
    599 

C:\Python\Python36_64b\lib\site-packages\ipywidgets\widgets\widget.py in send_state(self, key)
    480             state, buffer_paths, buffers = _remove_buffers(state)
    481             msg = {'method': 'update', 'state': state, 'buffer_paths': buffer_paths}
--> 482             self._send(msg, buffers=buffers)
    483 
    484     def get_state(self, key=None, drop_defaults=False):

C:\Python\Python36_64b\lib\site-packages\ipywidgets\widgets\widget.py in _send(self, msg, buffers)
    723         """Sends a message to the model in the front-end."""
    724         if self.comm is not None and self.comm.kernel is not None:
--> 725             self.comm.send(data=msg, buffers=buffers)
    726 
    727     def _repr_keys(self):

C:\Python\Python36_64b\lib\site-packages\ipykernel\comm\comm.py in send(self, data, metadata, buffers)
    119         """Send a message to the frontend-side version of this comm"""
    120         self._publish_msg('comm_msg',
--> 121             data=data, metadata=metadata, buffers=buffers,
    122         )
    123 

C:\Python\Python36_64b\lib\site-packages\ipykernel\comm\comm.py in _publish_msg(self, msg_type, data, metadata, buffers, **keys)
     63         data = {} if data is None else data
     64         metadata = {} if metadata is None else metadata
---> 65         content = json_clean(dict(data=data, comm_id=self.comm_id, **keys))
     66         self.kernel.session.send(self.kernel.iopub_socket, msg_type,
     67             content,

C:\Python\Python36_64b\lib\site-packages\ipykernel\jsonutil.py in json_clean(obj)
    189         out = {}
    190         for k,v in iteritems(obj):
--> 191             out[unicode_type(k)] = json_clean(v)
    192         return out
    193     if isinstance(obj, datetime):

C:\Python\Python36_64b\lib\site-packages\ipykernel\jsonutil.py in json_clean(obj)
    189         out = {}
    190         for k,v in iteritems(obj):
--> 191             out[unicode_type(k)] = json_clean(v)
    192         return out
    193     if isinstance(obj, datetime):

C:\Python\Python36_64b\lib\site-packages\ipykernel\jsonutil.py in json_clean(obj)
    189         out = {}
    190         for k,v in iteritems(obj):
--> 191             out[unicode_type(k)] = json_clean(v)
    192         return out
    193     if isinstance(obj, datetime):

C:\Python\Python36_64b\lib\site-packages\ipykernel\jsonutil.py in json_clean(obj)
    175 
    176     if isinstance(obj, list):
--> 177         return [json_clean(x) for x in obj]
    178 
    179     if isinstance(obj, dict):

C:\Python\Python36_64b\lib\site-packages\ipykernel\jsonutil.py in <listcomp>(.0)
    175 
    176     if isinstance(obj, list):
--> 177         return [json_clean(x) for x in obj]
    178 
    179     if isinstance(obj, dict):

C:\Python\Python36_64b\lib\site-packages\ipykernel\jsonutil.py in json_clean(obj)
    195 
    196     # we don't understand it, it's probably an unserializable object
--> 197     raise ValueError("Can't clean for JSON: %r" % obj)

ValueError: Can't clean for JSON: <matplotlib.figure.Figure object at 0x000001BDB3E9F438>
```

### PR DESCRIPTION
**Pull request by jasongrout**
Fixes #1960 

CC @vidartf

### CODE REVIEW

**Comment by jasongrout** [comment]
@vidartf - could you review this?

**Comment by vidartf** [comment]
LGTM. However, I pushed two commits:
- One to add some basic tests.
- One to replace some uses of `List` traits with `TypedTuple`. If this is considered breaking enough that it cannot be included in 7.2 I'm happy to remove it though.

**Comment by vidartf** [comment]
Oh, and `TypedTuple` should probably get a docstring.

**Comment by jasongrout** [comment]
> One to add some basic tests.

Thanks!!!

> One to replace some uses of List traits with TypedTuple. If this is considered breaking enough that it cannot be included in 7.2 I'm happy to remove it though.

I think it's fine. People should not be using list-based functionality in those traits, since changes don't get propagated.

**Pull request merged**
