### PR TITLE
re-export link and dlink from traitlets for consistency with the javascript api

### PR DESCRIPTION
**Pull request by rprimet**
…script API

### CODE REVIEW

**Comment by rprimet** [comment]
(related issue: #1809)

**Comment by jasongrout** [comment]
Thank you! Can we also delete the cell in the example where traitlets is imported?

**Comment by rprimet** [comment]
Good catch, thanks! This should be fixed now.

**Comment by jasongrout** [comment]
Thank you!

**Comment by SylvainCorlay** [comment]
Quick note @rprimet, your git configuration does not match your GitHub user email so that your account is not credited with this commit. Sorry for not catching that earlier.

**Comment by rprimet** [comment]
Ah thanks for that ! I'll update my git config.

**Pull request merged**
