### PR TITLE
Switch installing documentation dependencies to pip

### PR DESCRIPTION
**Pull request by pbugnion**
Building the docs currently fails because we exceed the 1GB allocated to us by readthedocs when installing the requirements with conda (issue #2706 and build failure [here](https://readthedocs.org/projects/ipywidgets/builds/10227852/)) .

This switches the installation to pip.

The docs now build correctly. See an example build [here](https://ipywidgets.readthedocs.io/en/fix-docs-build/).

Note that some of the pages don't display widgets because:
- nbsphinx adds the html-manager stable to the page
- this installs controls 1.5.3
- controls does not currently support StackedWidget.

(For reference, I built this on a branch in this repository rather than in my fork so I could trigger builds on readthedocs)

### CODE REVIEW

**Comment by pbugnion** [comment]
I'm adding this to the 8.0 milestone since we can't build a stable version of the docs otherwise.

**Comment by mwcraig** [comment]
> (For reference, I built this on a branch in this repository rather than in my fork so I could trigger builds on readthedocs)

Do you want me to ask RTD to turn on doc builds on PRs? It is a super-helpful feature but they are enabling it only by request for now.

**Comment by pbugnion** [comment]
> Do you want me to ask RTD to turn on doc builds on PRs? It is a super-helpful feature but they are enabling it only by request for now.

I didn't know this was possible. I had to manually turn on building for this `fix-docs-build` branch, which is pretty ugly.

Yes, that'd be great! I can also reach out to them since you already have a lot on your plate?

**Comment by mwcraig** [comment]
Already emailed :) I had a copy handy from a few weeks ago when I requested it for another repo. It is really magical.

**Comment by mgeier** [comment]
> nbsphinx adds the html-manager stable to the page

By default, `nbsphinx` uses whatever is in `ipywidgets.embed.DEFAULT_EMBED_REQUIREJS_URL`.
In the current `master` version that's:

https://github.com/jupyter-widgets/ipywidgets/blob/9f6d5de1025fb02e7cad16c0b0cd462614482c36/ipywidgets/_version.py#L17

If you want to use a different version (URL or file), see https://nbsphinx.readthedocs.io/en/0.5.0/usage.html#nbsphinx_widgets_path.

**Comment by pbugnion** [comment]
@mwcraig Thank you!

@mgeier : moving the conversation around how to set the embed manager to a separate issue, since it's a bit orthogonal to this.

**Comment by mgeier** [comment]
> the problem is we don't have a built version of the html manager that we can use

Yeah, that's a pity.

> Regardless, that's a bit orthogonal to this issue.

It indeed is, I've created a new issue for that: #2711

**Comment by mwcraig** [comment]
Closing/reopening to (hopefully) trigger a ReadTheDocs build...

**Comment by mwcraig** [comment]
Close/reopen again after updating the RTD webhook

**Comment by pbugnion** [comment]
Nice, that's brilliant!

Thanks to Matt, we now explicitly build the PR on readthedocs. cf: https://external-builds.readthedocs.io/html/ipywidgets/2708/index.html for the docs for this PR.

**Comment by jasongrout** [comment]
Thanks!

**Pull request merged**
