### PR TITLE
BUG: comm.kernel should be None when it has no kernel

### LINKED ISSUE #14: AttributeError: 'DummyComm' object has no attribute 'kernel'
@maartenbreddels , using your #13 fix, now I get this downstream in Jdaviz. Hope you can help. Thanks!

`AttributeError: 'DummyComm' object has no attribute 'kernel'`

Example log: https://github.com/spacetelescope/jdaviz/actions/runs/4482254804/jobs/7895309668?pr=2104

xref https://github.com/spacetelescope/jdaviz/pull/2104

### PR DESCRIPTION
**Pull request by pllim**
Hopefully this will fix https://github.com/ipython/comm/issues/14 but I don't know for sure.

cc @maartenbreddels

### CODE REVIEW

**Review by martinRenou — APPROVED** [review]
Thanks!

**Comment by pllim** [comment]
I don't understand this error. I did not touch the change log:

```
[warn] docs/source/changelog.md
[warn] Code style issues found in the above file. Forgot to run Prettier?
```

**Comment by martinRenou** [comment]
It will be fixed by https://github.com/jupyter-widgets/ipywidgets/pull/3734

**Comment by pllim** [comment]
Thank you for the merge! Please let me know when this patch is released so I can try it out downstream. 🙇‍♀️

**Pull request merged**
