### PR TITLE
[WIP] tslint edit example rules for no-unused-variable

### PR DESCRIPTION
**Pull request by cnishina**

### CODE REVIEW

**Comment by pbugnion** [comment]
Any reason for adding the `no-unused-variable` rule?

**Comment by cnishina** [comment]
Without `no-unused-variable`, the following lint warnings happen. There are no tests to validate that these can be removed so the best assumption is that they belong and the lint errors should be ignored.

web-tmpnb:

```
ipywidgets/examples/web-tmpnb/src/index.ts
ERROR: 46:21  no-unused-variable  'editor' is declared but never used.
ERROR: 57:21  no-unused-variable  'manager' is declared but never used.
```

web3:

```
ipywidgets/examples/web3/src/index.ts
ERROR: 33:13  no-unused-variable  'editor' is declared but never used.

ipywidgets/examples/web3/src/manager.ts
ERROR: 18:5   no-unused-variable  'requirePromise' is declared but never used.
```

**Comment by jasongrout** [comment]
The web-tmpnb example is currently broken (noted in the example README) - that's why it's only half-written right now.

For both examples, the `editor` variable doesn't need to be stored - we could just call the CodeMirror function.

We can delete the requirePromise function in web3. It now uses the HTMLManager, and should import those functions from the lib-embed.ts defined in the html manager package.

**Comment by jasongrout** [comment]
And for now, we can just not store the manager created in web-tmpnb to fix the linting error.

**Comment by cnishina** [comment]
I'll need to update this PR soon.

**Comment by jasongrout** [comment]
Ping on this - do you want to update it?

**Comment by cnishina** [comment]
Sure. I seem to have been very busy lately. I haven't forgotten about this.

**Comment by jtpio** [comment]
Closing, as we have now moved to ESLint!

See https://github.com/jupyter-widgets/ipywidgets/pull/2657 and https://github.com/jupyter-widgets/ipywidgets/pull/2700 for more info.

**Pull request closed without merging**
