### PR TITLE
if moduleName contains a slash, use a different module/path

### PR DESCRIPTION
**Pull request by maartenbreddels**
This is useful if a package contains multiple widget extensions (I use this for ipysheet).
For instance, use:
`_model_module = Unicode('ipysheet/renderer').tag(sync=True)`
The embed manager will try got get `ipysheet/renderer.js` from the server its running on (which is a valid request, and useful for local testing), if that fails it will fetch:
`https://unpkg.com/ipysheet@semver/dist/renderer.js`

### CODE REVIEW

**Comment by vidartf** [comment]
Does this need to special case "@my-namespace/mymodule" ?

**Comment by maartenbreddels** [comment]
Indeed, good call. Do you see any other issues with this?

**Comment by jasongrout** [comment]
The only other issue I see with this is that it still inserts the `dist/` - is there a way we don't have to hardcode that portion either? I don't see a way to have it nicely support both the other widget managers, but perhaps you have an idea?

**Comment by jasongrout** [comment]
> I think the 'dist/' part is ok, I see it as a manager specific implementation.

Oh right - it is very specific to how the html manager is fetching things.

**Comment by jasongrout** [comment]
Looks good to me, then. Thanks!

**Pull request merged**
