### PR TITLE
Centralize output widget docs

### PR DESCRIPTION
**Pull request by pbugnion**
Addresses issue #1935.

The output widget is powerful since it allows leveraging Jupyter's rich display mechanism. Documentation and recipes for the output widget were scattered across many places in the documentation. This PR tries to centralise mentions of the output widget, and add other contributions previously found in issues and gists.

In particular, we create a new example notebook with:
 - What was previously under the output widget in [widget list](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#Output)
 - The [section](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Asynchronous.html#Interacting-with-output-widgets-from-background-threads) on updating output widgets asynchronously
 - This [recipe](https://github.com/jupyter-widgets/ipywidgets/issues/1936) for creating a logging handler that writes to the output widget
 - This [gist](https://gist.github.com/anonymous/eb176705a103517179b4f57b6201df1d) with information on clearing the widget output, appending to the widget directly and controlling the output of `interact`.

----
Left to do:

- [x] it looks like there is an extra left margin in your screenshot. Is the output widget not deleting that left margin? (this seems to predate this PR -- I've opened issue #2025 to fix it).
- [x] The background thread issue is a bit more complicated - threaded output in the ipython kernel isn't cleanly supported, since it's not just scoped to a thread, but also scoped to the execution in the main thread. In other words, if you start a background thread, the background thread output goes into whatever output the main thread happens to be sending things to. What the output widget does is offer a way to redirect that background threaded output to somewhere we choose. We can't rely on the display() mechanism for this since it suffers the problem above. To get around this, we append directly to the output widget, bypassing the ipython display mechanism.
- [x] in debugging callbacks, "An effective tool for debugging this" - it's not clear what "this" refers to - perhaps a small bit of explanation, or at least just replacing "this"?
- [x] Can we add a sentence explaining the `wait=True` argument to the capture decorator?
- [x] Perhaps a word should be added about #1811 - that append_display... doesn't work with widgets for right now, instead explicitly use display().
----

This is what the output looks like:

demo3

### CODE REVIEW

**Comment by jasongrout** [comment]
Wow, nice! Very nice!!!!

A couple of things:

1. it looks like there is an extra left margin in your screenshot. Is the output widget not deleting that left margin?
2. The background thread issue is a bit more complicated - threaded output in the ipython kernel isn't cleanly supported, since it's not just scoped to a thread, but also scoped to the execution in the main thread. In other words, if you start a background thread, the background thread output goes into whatever output the main thread happens to be sending things to. What the output widget does is offer a way to redirect that background threaded output to somewhere we choose. We can't rely on the display() mechanism for this since it suffers the problem above. To get around this, we append directly to the output widget, bypassing the ipython display mechanism.
3. in debugging callbacks, "An effective tool for debugging this" - it's not clear what "this" refers to - perhaps a small bit of explanation, or at least just replacing "this"?
4. Can we add a sentence explaining the wait=True argument to the capture decorator?
5. Perhaps a word should be added about https://github.com/jupyter-widgets/ipywidgets/issues/1811 - that append_display... doesn't work with widgets for right now, instead explicitly use display().

**Comment by pbugnion** [comment]
Thanks for the feedback! I'll look into it over the next few days.

**Comment by maartenbreddels** [comment]
great work pascal!
side questions: how do you make a screenshot like the (except on a crazy big monitor in landscape)

**Comment by jasongrout** [comment]
Firefox and Chrome both have facilities for making screenshots of an entire page: https://developer.mozilla.org/en-US/docs/Tools/Taking_screenshots

**Comment by pbugnion** [comment]
Thanks!

Being able to take whole page screenshots is super useful for docs -- I learnt this from a work colleage. I use a Chrome extension called [fireshot](https://chrome.google.com/webstore/detail/take-webpage-screenshots/mcbpblocgmgfnpjjppndjkmgjaogfceg?hl=en), but I'll definitely look into the links Jason posted.

**Comment by pbugnion** [comment]
For the extra left margin, I've opened issue #2025 . The error seems to predate this PR: it's already present on [docs built off master](http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#Output).

I'm happy to tackle that next, but given that it (presumably) isn't a regression introduced by this PR, and given that merge conflicts in the docs notebooks can be fairly painful, I'd like to do it off a separate branch (so we can merge this as soon as possible).

That aside, I think this PR is ready for another review.

**Comment by jasongrout** [comment]
Very nice! Thanks!

**Comment by pbugnion** [comment]
Great, thanks a lot for the help!

**Pull request merged**
