### PR TITLE
use np.array_equal install of np.equal

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by dmadeka** [comment]
@SylvainCorlay this caused a number of bugs in bqplot. Can we have a minor release for this PR?

**Comment by jasongrout** [comment]
Done! 7.0.0a11

**Comment by dmadeka** [comment]
@jasongrout yes! on PyPi using --pre? bqplot's dependencies will need to be updated because a lot of things are breaking right now

**Comment by jasongrout** [comment]
Sure, let's update bqplot dependencies.

**Pull request merged**
