### PR TITLE
Allow Output widget in html manager to render state updates

### PR DESCRIPTION
**Pull request by MrBago**
This PR adds a listener to the output widget in html-manger to update the Output Area when new outputs are added to the widget in the kernel. The PR also adds a unit test and updates the web3 example to demonstrate the change.

### CODE REVIEW

**Comment by jasongrout-db** [comment]
> **Lint / Lint (pull_request) ** Failing after 34s — Lint

We should really get a bot to run lint for us and update PRs automatically...

@MrBago - you can just run `yarn run lint` in the repo root and commit the changes to get the lint test to pass.

**Comment by ianhi** [comment]
> We should really get a bot to run lint for us and update PRs automatically...

I set up pre-commit.ci on ipympl and several other repos and find it to be quite nice. See https://github.com/matplotlib/ipympl/pull/362

**Comment by jasongrout** [comment]
Thanks @MrBago. This looks great. The image zoom was mesmerizing.

For those who have always wondered, this is what a Jupyter Logo looks like at 1x1 pixels on a hidpi screen (magnified by a factor of 4 to see it easier):

Screen Shot 2022-02-07 at 15 24 32

**Review by jasongrout — APPROVED** [review]

**Comment by jasongrout** [comment]
@meeseeksdev please backport to 7.x

**Pull request merged**
