### PR TITLE
Use pytest instead of nose for tests

### PR DESCRIPTION
**Pull request by mwcraig**
The main reason for making this switch is that nose is no longer being developed, though I also find the pytest style of writing tests a little cleaner.

### CODE REVIEW

**Comment by jasongrout** [comment]
Thank you!!

**Comment by jasongrout** [comment]
> Would you mind getting rid of those too?

I had a few extra minutes, so fixed those mentions of nose. I think we're good to go if tests pass. Thanks!

**Comment by jasongrout** [comment]
Thanks again!

**Comment by mwcraig** [comment]
My pleasure, thanks for the cleanup!

**Pull request merged**
