### PR TITLE
Make `d3-format` dependency consistent with JLab's

### PR DESCRIPTION
**Pull request by mprogram**
Follows-up and closes (#2184)

### CODE REVIEW

**Comment by jasongrout** [comment]
Just curious - did you check that the readouts work just fine still when specifying a custom format?

**Comment by mprogram** [comment]
Frankly, I couldn't have time to check. It was midnight in my time zone, and a long day coming next morning. I only checked for the Travis CI build to pass.

**Comment by jasongrout** [comment]
Thanks for sending in the PR anyway. I'll check it as part of the review.

**Comment by jasongrout** [comment]
Works great for me! Thanks!

**Pull request merged**
