### PR TITLE
Fix downward arrow misalignment for combobox

### PR DESCRIPTION
**Pull request by xiaochen-db**
Remove the problematic line-height style that affected combobox downward arrow. 

Before the change:
Screen Shot 2022-02-02 at 5 41 22 PM

After the change:
Screen Shot 2022-02-02 at 5 48 57 PM

### CODE REVIEW

**Comment by jasongrout** [comment]
Though I didn't see any difference visually when originally trying this out, our visual regression tests are failing. Here's what I'm seeing when I investigate manually on Chrome, which matches up with what the tests are showing (a 1-pixel difference in the screenshots).

With the line-height (status quo):
Screen Shot 2022-02-08 at 02 09 59

Without the line-height (i.e., after this PR):
Screen Shot 2022-02-08 at 02 10 24

**Comment by jasongrout** [comment]
With Safari, we have the same height of that particular element whether or not the line-height is active, however when the line-height is active, we also have a scrollbar to the right of the widget, and no scrollbar when the line-height is not active the scrollbar disappears:

Safari, with line-height active:
Screen Shot 2022-02-08 at 02 51 41

Safari, without line-height active:
Screen Shot 2022-02-08 at 02 51 56

**Review by SylvainCorlay — APPROVED** [review]

**Comment by jasongrout** [comment]
Thanks!

**Comment by jasongrout** [comment]
@meeseeksdev please backport to 7.x

**Pull request merged**
