### PR TITLE
Package license files

### PR DESCRIPTION
**Pull request by jakirkham**
Make sure the license files get included in the various `sdist`s.

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks!

**Comment by jasongrout** [comment]
Sorry, I've been busy with JupyterLab lately. Looking at this more closely, perhaps we should solve https://github.com/jupyter-widgets/ipywidgets/issues/1701 first to clear up the confusion rather than propagating it into the packages. Let me look at that first (e.g., https://github.com/jupyter-widgets/ipywidgets/pull/1706)

**Comment by jakirkham** [comment]
How should this be update now that PR ( https://github.com/jupyter-widgets/ipywidgets/pull/1706 ) is merged?

**Comment by jasongrout** [comment]
Thanks! Fixed by #2133.

**Pull request closed without merging**
