### PR TITLE
Make controller button and axis a dom widget.

### PR DESCRIPTION
**Pull request by jasongrout**
CC @SylvainCorlay - what do you think?

CC @maartenbreddels - this should fix the bug noted in https://github.com/jupyter-widgets/ipywidgets/issues/1620

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
👍

**Comment by maartenbreddels** [comment]
I don't think it fixes it, it will make #1620 show up in core ipywidgets :) but I think it requires #1621

**Comment by jasongrout** [comment]
@SylvainCorlay approved in gitter.

**Comment by jasongrout** [comment]
@maartenbreddels -sorry, I mean fixes *a* bug in #1620.

**Comment by maartenbreddels** [comment]
A, like that, yes, true.

**Pull request merged**
