### PR TITLE
Revamp event handling in text boxes and add continuous_update option

### LINKED ISSUE #584: Add a continuous_update option for text widgets
The sliders have a continuous_update option that only triggers a value change when the user stops dragging a slider: https://github.com/ipython/ipywidgets/blob/master/ipywidgets/widgets/widget_int.py#L155. Likewise, the text boxes should have an option to only update the value when the text box is blurred, or maybe when the user presses enter in a one-line textbox (sort of the equivalent of the on_submit handler textboxes currently have).

### PR DESCRIPTION
**Pull request by jasongrout**
- [x] Check the width of float/int/bounded text boxes now - they seem to be shorter.
- [x] deprecate the on_submit handler for text boxes, and handle the events similar to how things are done in this PR (with input and change events).

Also, specialize those inputs to type number, and add a step option.

 I default continuous_update to False for the textboxes because I figured if people were typing, that's typically what is wanted.

FIxes #584 and #1401.

### CODE REVIEW

**Comment by jasongrout** [comment]
CC @mpacer

**Comment by jasongrout** [comment]
@mpacer (or anyone), if you have a better name than "continuous_update", I'm all ears...

**Comment by mpacer** [comment]
I can give it a spin before the end of the day :) thanks for getting to this so quickly!

**Comment by mpacer** [comment]
I think it would help to include in the docstrings what the default behaviour is (i.e., when `continuous_update` is set to off). E.g., does it send when either you hit enter/return or change focus as asked for in #584?

**Comment by mpacer** [comment]
Also it'd be good to have an example in the docs of both kinds of behaviour. This shouldn't need backend connections as far as I can tell so it should render nicely in the docs with an appropriate example.

**Comment by jasongrout** [comment]
Oh, the issue there is that when you delete, it recognizes it's not a number, so it's patiently waiting for you to type something that *is* a number.

**Comment by jasongrout** [comment]
(that's also why it resets when you click out - if the value is not valid, it resets to the previous value)

**Comment by jasongrout** [comment]
> Oh, the issue there is that when you delete, it recognizes it's not a number, so it's patiently waiting for you to type something that is a number.

What if we put in a placeholder like "Type a number" or something? That would show if you deleted everything in the box. Would that be enough of a hint?

**Comment by jasongrout** [comment]
@mpacer, I updated the docs. Thoughts?

**Comment by jasongrout** [comment]
Merging - @mpacer, feel free to open another issue if you see something we missed.

**Pull request merged**
