### PR TITLE
Create and upload reference screenshots on CI failure

### PR DESCRIPTION
**Pull request by jtpio**
So the new reference screenshots can be retrieved from the GitHub Actions artifacts and updated if needed.

### CODE REVIEW

**Comment by jtpio** [comment]
This also updates to the latest version of galata that includes some fixes.

**Comment by jtpio** [comment]
CI is green, marking as ready for review.

**Review by mbektas — APPROVED** [review]
LGTM!

**Comment by jasongrout** [comment]
Thanks! Does this fix the test failure we are seeing in #2954?

**Comment by jtpio** [comment]
I think so since these are timeout related that the new galata version should now be handling better.

**Pull request merged**
