### PR TITLE
Grid layout

### PR DESCRIPTION
**Pull request by SylvainCorlay**
screen shot 2018-07-05 at 12 18 18 am

### CODE REVIEW

**Comment by Madhu94** [comment]
Both commits taken together, my changes are effectively wiped out and might as well not be included ! :(  
The changes bear close resemblance to what the state was when I made this comment https://github.com/jupyter-widgets/ipywidgets/issues/1942#issuecomment-381471396 => Basically GridBox inherited from Box, and all CSS properties (not redundant) were in Layout.

Could you please let me know what were the reasons for proposing it should be a separate class ?
Thanks.

**Comment by SylvainCorlay** [comment]
> Both commits taken together, my changes are effectively wiped out and might as well not be included ! :(
> The changes bear close resemblance to what the state was when I made this comment #1942 (comment) => Basically GridBox inherited from Box, and all CSS properties (not redundant) were in Layout.

Yeah, I am really sorry if you spent too much time on separating it in multiple widgets.

So I was playing with your implementation yesterday and my initial change was to group things using the shorthand properties like elsewhere in ipywidgets. Although I did not go all the way, because there is a catch-all `grid` short hand property that is pretty hard to deal with.

Then we discussed with @jasongrout and went back & forth between the initial design of adding grid properties to layout that I think you proposed and your PR.

In any case, I would be happy to squash my commit into yours especially as you pretty much had this version already earlier.

From what I gather in the original thread, you seem to lean towards a single layout attribute. Also, coming back to your proposal of having a hierarchy of `Layout` types, it seems that at least the item properties should be in the base one, and maybe only the container grid properties should be in the `GridBoxLayout` class.

What do you think? Should we go ahead with something like this or would you like to iterate more upon it in the earlier PR?

**Comment by Madhu94** [comment]
> From what I gather in the original thread, you seem to lean towards a single layout attribute. Also, coming back to your proposal of having a hierarchy of Layout types, it seems that at least the item properties should be in the base one, and maybe only the container grid properties should be in the GridBoxLayout class.    

The current state is similar to how ``Box`` is implemented though.  

> Should we go ahead with something like this or would you like to iterate more upon it in the earlier PR?  

No, please go ahead with your changes, my apologies if the earlier comment seemed a little aggressive.

**Comment by SylvainCorlay** [comment]
>> Should we go ahead with something like this or would you like to iterate more upon it in the earlier PR?
>>
>
> No, please go ahead with your changes, my apologies if the earlier comment seemed a little aggressive.

Not at all!

**Comment by SylvainCorlay** [comment]
screen shot 2018-07-04 at 7 55 13 pm

**Comment by SylvainCorlay** [comment]
@jasongrout this is ready to go!

**Pull request merged**
