### PR TITLE
[WIP] GridBox widget

### PR DESCRIPTION
**Pull request by Madhu94**
For #1942 

Let me know if this looks fine, I've gone with @SylvainCorlay's suggestion.

### CODE REVIEW

**Comment by mlucool** [comment]
Any updates on this?

**Comment by SylvainCorlay** [comment]
I plan on reviewing this next week. I am off for a couple of days.

**Comment by Madhu94** [comment]
@SylvainCorlay  Did you get time to check this ?

**Comment by jasongrout** [comment]
Closed in favor of #2107. If this should remain open, let us know and we can reopen it.

**Pull request closed without merging**
