### PR TITLE
Automatic fixes from tslint

### PR DESCRIPTION
**Pull request by jasongrout**
Thanks to @cnishina getting tslint working, we get some automatic style fixes for free with `tslint --fix`. I'm pushing and merging these since there are no outstanding PRs on the examples.

### CODE REVIEW

**Comment by cnishina** [comment]
```
Package integrity failures:
{
 "examples/web3": [
 "Unused package: @jupyter-widgets/controls"
 ]
}
```

I also ran into this when I did a rebase for the first attempt at tslint.

**Comment by jasongrout** [comment]
Thanks, I'm working on it.

**Comment by jasongrout** [comment]
Basically, the web3 example was improperly including only the widget controls css - that should be provided by the html manager. Unwinding that chain is going to take a bit more time than I have today.

**Comment by jasongrout** [comment]
Actually, let's make the dependency issue a different issue to fix, and work around it for now.

**Pull request merged**
