### PR TITLE
Raise error when __copy__ method is used on base widget class

### PR DESCRIPTION
**Pull request by mmc1718**
- Base widget class does not have a copy implementation and should raise an error as per discussion in #2352 
- Test case added in test_widget.py
- Resolves issue #2352

### CODE REVIEW

**Comment by ibdafna** [comment]
@mmc1718 Many thanks for the contribution! Would you be able to run a quick lint pass on this?

**Comment by mmc1718** [comment]
Thanks @ibdafna, I have run prettier and `yarn lint:check` locally and hopefully it should pass now :)

**Review by ibdafna — APPROVED** [review]
Thank you!

**Review by JennPlothow — COMMENTED** [review]
[jupyterlab-licenses (5).md](https://github.com/jupyter-widgets/ipywidgets/files/12645292/jupyterlab-licenses.5.md)

**Pull request merged**
