### PR TITLE
WIP Export the @jupyter-widgets/base and @jupyter-widgets/controls modules in html manager

### PR DESCRIPTION
**Pull request by jasongrout**
Still very much a work in progress, but pushing here so there is a backup and people can see what I'm working on.

See #1551

### CODE REVIEW

**Comment by jasongrout** [comment]
This is a bit more complicated: The html manager has several 'entry points'. It's not completely clear where to put the code that loads require on the page if it isn't already there. The code that exposes the htmlmanager's base and controls library of course should be *after* the code that ensures requirejs is on the page.

  - A library (`index`) that exports the html manager and a simple function for generating an embed script
  - A script (`embed-webpack`) that can just be included on a page, which automatically goes through every script tag representing widget state/views and renders them. This script also puts require on the page if it's not there.

**Comment by jasongrout** [comment]
I ended up:

1. Webpacking a new html manager package into index.js
1. Making the embed script (now called embed.js) responsible for loading all of the scripts (base, controls, html manager) from unpkg.com using require.

**Comment by stonebig** [comment]
does it mean jupyterlab is unsuable without internet connection ?

**Comment by jasongrout** [comment]
> does it mean jupyterlab is unsuable without internet connection ?

This PR only deals with embedding widgets on a webpage, it has nothing to do with JupyterLab. This is only about enabling the workflow of 'get the minimal widgets infrastructure up on a page on the internet'. As a convenience, the embed.js provided here loads all of the widget infrastructure from unpkg.com, so you don't need anything installed locally.

**Comment by jasongrout** [comment]
To really test this out, I'm going to have to merge and release a package. We'll iterate in another PR if needed.

**Pull request merged**
