### PR TITLE
remove class `jupyter-widgets` from jp-OutputArea-output node

### PR DESCRIPTION
**Pull request by qzchenwl**
Fix issue #2499

### CODE REVIEW

**Comment by jasongrout** [comment]
The `jupyter-widgets` class is meant to be the very base class for jupyter widgets that sets some CSS defaults (such as font color, etc.). However, I notice that it is set a *lot* in the code, at multiple levels. I think we need to be more deliberate about how we are using it (e.g., is it convention that it is applied at the top-level widget? At the root node of each widget? Above the entire widget hierarchy?)

Also, perhaps we could just change the overflow setting. It was set to `visible` in 2016 (https://github.com/jupyter-widgets/ipywidgets/pull/919).

Whatever change we decide on, I think we need to carefully examine lots of examples using widgets to understand the ramifications of this change. We've seen this before with seemingly small changes that had large ramifications, especially in CSS.

**Comment by SylvainCorlay** [comment]
I think that the `jupyter-widgets` CSS class is only meant for the top-level DOM elements.

I would be in favor of this, but I need to double check that everything is fine in the PR.

**Comment by jasongrout** [comment]
I did some initial investigations. Visually, removing this class removes a layer of padding around the entire set of widgets.

I'm a little curious about the css for this class of `overflow: visible`, which is the main point here. In general, it seems odd to let the content flow out of the widget's containing box, so I'm not sure why it is set at all. Tracing back through the history, it seems this `overflow: visible` was added in https://github.com/jupyter-widgets/ipywidgets/pull/796, and it's not clear what problem it was solving.

**Comment by jasongrout** [comment]
> I'm a little curious about the css for this class of `overflow: visible`, which is the main point here. In general, it seems odd to let the content flow out of the widget's containing box, so I'm not sure why it is set at all. Tracing back through the history, it seems this `overflow: visible` was added in #796, and it's not clear what problem it was solving.

But this is a different issue than this one, i.e., `.jupyter-widgets` being applied at the top level.

Let's merge this and address any other problems that come up. Thanks again @qzchenwl!

**Pull request merged**
