### PR TITLE
Update test_append_display_data for ipython 8.11.0

### LINKED ISSUE #3711: test_append_display_data fails
```
___________________________ test_append_display_data ___________________________

    def test_append_display_data():
        widget = widget_output.Output()

        # Try appending a Markdown object.
        widget.append_display_data(Markdown("# snakes!"))
        expected = (
            {
                'output_type': 'display_data',
                'data': {
                    'text/plain': '<IPython.core.display.Markdown object>',
                    'text/markdown': '# snakes!'
                },
                'metadata': {}
            },
        )
        assert widget.outputs == expected, repr(widget.outputs)

        # Now try appending an Image.
        image_data = b"foobar"
        image_data_b64 = 'Zm9vYmFy\n'

        widget.append_display_data(Image(image_data, width=123, height=456))
        expected += (
            {
                'output_type': 'display_data',
                'data': {
                    'image/png': image_data_b64,
                    'text/plain': '<IPython.core.display.Image object>'
                },
                'metadata': {
                    'image/png': {
                        'width': 123,
                        'height': 456
                    }
                }
            },
        )
>       assert widget.outputs == expected, repr(widget.outputs)
E       AssertionError: ({'output_type': 'display_data', 'data': {'text/plain': '<IPython.core.display.Markdown object>', 'text/markdown': '# snakes!'}, 'metadata': {}}, {'output_type': 'display_data', 'data': {'image/png': 'Zm9vYmFy', 'text/plain': '<IPython.core.display.Image object>'}, 'metadata': {'image/png': {'width': 123, 'height': 456}}})
E       assert ({'output_type': 'display_data', 'data': {'text/plain': '<IPython.core.display.Markdown object>', 'text/markdown': '# snakes!'}, 'metadata': {}}, {'output_type': 'display_data', 'data': {'image/png': 'Zm9vYmFy', 'text/plain': '<IPython.core.display.Image object>'}, 'metadata': {'image/png': {'width': 123, 'height': 456}}}) == ({'output_type': 'display_data', 'data': {'text/plain': '<IPython.core.display.Markdown object>', 'text/markdown': '# snakes!'}, 'metadata': {}}, {'output_type': 'display_data', 'data': {'image/png': 'Zm9vYmFy\n', 'text/plain': '<IPython.core.display.Image object>'}, 'metadata': {'image/png': {'width': 123, 'height': 456}}})
E         At index 1 diff: {'output_type': 'display_data', 'data': {'image/png': 'Zm9vYmFy', 'text/plain': '<IPython.core.display.Image object>'}, 'metadata': {'image/png': {'width': 123, 'height': 456}}} != {'output_type': 'display_data', 'data': {'image/png': 'Zm9vYmFy\n', 'text/plain': '<IPython.core.display.Image object>'}, 'metadata': {'image/png': {'width': 123, 'height': 456}}}
E         Full diff:
E           (
E            {'data': {'text/markdown': '# snakes!',
E                      'text/plain': '<IPython.core.display.Markdown object>'},
E             'metadata': {},
E             'output_type': 'display_data'},
E         -  {'data': {'image/png': 'Zm9vYmFy\n',
E         ?                                  --
E         +  {'data': {'image/png': 'Zm9vYmFy',
E                      'text/plain': '<IPython.core.display.Image object>'},
E             'metadata': {'image/png': {'height': 456, 'width': 123}},
E             'output_type': 'display_data'},
E           )

ipywidgets/widgets/tests/test_widget_output.py:223: AssertionError

```

### PR DESCRIPTION
**Pull request by frenzymadness**
Fixes https://github.com/jupyter-widgets/ipywidgets/issues/3711

### CODE REVIEW

**Comment by kellietay** [comment]
Thank you so much, we appreciate your contribution! Can you help to fix the 1 more test that failed?

**Comment by stevejpurves** [comment]
it kind of looks like there is only one place to change the test here though, and that is the change included in this PR?
Noting that the test for python 3.10 passes (ipykernel `6.21.2`) while python 3.7 fails (it loads ipykernel `6.16.2`) is this because our test environment is too loose and the recent `ipykernel` change to string the newline isn't installed in the 3.7 environment?

**Comment by frenzymadness** [comment]
IIRC the problem is that ipython 8 does not support Python 3.7 so the test for Python 3.7 installs ipython 7.34 and that version works with the old test. Should I make the test work with both major versions of ipython?

**Comment by maartenbreddels** [comment]
@martinRenou this explain what why we needed the fix in https://github.com/jupyter-widgets/ipywidgets/pull/3720

Thanks for the PR @frenzymadness , but we accidently re-discovered this.

**Pull request closed without merging**
