### PR TITLE
Better way to use require fallback?

### PR DESCRIPTION
**Pull request by vidartf**
See discussion in https://github.com/jovyan/pythreejs/issues/171 .

### CODE REVIEW

**Comment by jasongrout** [comment]
@maartenbreddels - can you review this one, as you were involved in the issue over in pythreejs?

**Comment by jasongrout** [comment]
This can also go into a patch release of html manager, so we don't have to rush it for 7.2.

**Comment by maartenbreddels** [comment]
Let me check this one, I think the idea is solid.

**Comment by maartenbreddels** [comment]
Ok, the issue is that require already 'knows' 'jupyter-threejs' failed, since it requested it before doing the CDN request (it queried for ./jupyter-threejs.js), and refuses to do so again. This can be fixed using `require.undef('jupyter-threejs')`, say in requireLoader, after the catch.

**Comment by maartenbreddels** [comment]
Didn't work, you need to take off the `.js` part, sth like this:
```
            var url = moduleNameToCDNUrl(moduleName, moduleVersion)
            conf.paths[moduleName] = url.substring(0, url.length-3);
```

**Comment by vidartf** [comment]
Since the function is not exported, I just removed the `.js` part from the return value.

**Comment by vidartf** [comment]
This works for me locally now.

**Comment by maartenbreddels** [comment]
yes works here too.

**Pull request merged**
