### PR TITLE
Use `yarn` instead of `npm` in the dev install script

### PR DESCRIPTION
**Pull request by peristeri**
With the dependency to `jupyterlab` which uses `yarn` to build its js files. Switching to `yarn` solved the error of: `base.ts(5,27): error TS2307: Cannot find module '@jupyterlab/services'`

Came across this error when helping with #1827

### CODE REVIEW

**Comment by jzf2101** [comment]
@jasongrout I'm cool with this if you are

**Comment by jasongrout** [comment]
Looks good to me. Thanks!

**Comment by vidartf** [comment]
Does this mean that all projects that depend on Jupyterlab now have to switch from npm to yarn?

**Comment by blink1073** [comment]
No, I think the underlying issue here is that you can't mix `npm install` and `yarn`.  Consumers of jlab packages can use whichever they wish.

**Pull request merged**
