### PR TITLE
Update for JupyterLab 0.28

### LINKED ISSUE #1760: Compatible with JupyterLab 0.28
JupyterLab just released 0.28 and currently release of @jupyter-widgets/jupyterlab-manager@0.27.1 is not compatible.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #1760

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks! I think @jupyterlab/services usually needs to be bumped as well: https://github.com/blink1073/ipywidgets/blob/41a287803f3bfdc1091a7f027725b39d0bb11721/packages/base/package.json#L58

(and a new release of all of the js packages, etc.)

I can work on this tomorrow too.

**Comment by blink1073** [comment]
Ah, I had tested locally using `jupyter labextension install .`.

**Comment by jasongrout** [comment]
We'll definitely appreciate it when `@jupyterlab/services` stabilizes!

**Comment by ktong** [comment]
Thanks @blink1073. probably the version also need change to 0.28.0 in https://github.com/blink1073/ipywidgets/blob/1f928a0b6f7cb27ca3919b1c925eda39853ec4dc/packages/jupyterlab-manager/package.json

**Comment by blink1073** [comment]
That is done as part of the release process after the PR is merged

**Comment by jasongrout** [comment]
Thanks! This looks good to me.

**Comment by jasongrout** [comment]
I just released new versions of everything affected. `@jupyter-widgets/jupyterlab-manager` 0.28 should be compatible with jupyterlab 0.28.

Thanks again @blink1073.

**Comment by blink1073** [comment]
Confirmed!  👍

**Pull request merged**
