### PR TITLE
Set default layout to {} at frontend

### PR DESCRIPTION
**Pull request by maartenbreddels**
fixes https://github.com/jupyter-widgets/ipywidgets/issues/1620

### CODE REVIEW

**Comment by jasongrout** [comment]
Doesn't style have the same issue?

**Comment by maartenbreddels** [comment]
That's a bit confusing, DOMWidget doesn't have a style attribute (on the backend), but some subclasses do. I don't feel comfortable removing it so close before a release.

**Comment by jasongrout** [comment]
Oh yeah - the fact that domwidget has style in the browser is an implementation detail, not part of the spec. We likely will have the same issue on any widgets that actually have a (nontrivial) style attribute.

**Comment by jasongrout** [comment]
Can you also add a default of `style = {}` for ButtonModel, DescriptionModel, FloatSliderModel, FloatProgressModel, FloatRangeSliderModel, IntSliderModel, IntProgressModel, IntRangeSliderModel, ToggleButtonsModel?

**Comment by jasongrout** [comment]
In general, I'm not sure new_widget should be transferring the defaults.

**Comment by jasongrout** [comment]
@maartenbreddels - what if we don't sync the defaults? i.e., what if we change https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/base/src/manager-base.ts#L284 to have the options.drop_defaults (see https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/base/src/widget.ts#L335)

**Comment by jasongrout** [comment]
This would rely on the defaults being *exactly* the same between the frontend and backend, otherwise there will be inconsistent state, of course. Or perhaps the kernel defaults would be sent over, since they wouldn't be in the property_lock. That might be better anyway.

**Comment by jasongrout** [comment]
@maartenbreddels - can you try not syncing the defaults instead of the change you made to the layout default?

**Comment by maartenbreddels** [comment]
That's a much better plan I think. I'll first try to confirm that #1622 introduces the bug seen in #1621.

**Comment by maartenbreddels** [comment]
It works, I wouldn't be surprised if this will show up other bugs though where defaults are not properly set on both sides. But otoh, otherwise they only show up when doing embedding, this will make them show up earlier.

**Comment by jasongrout** [comment]
Actually, thinking more about it, this may introduce a subtle race condition. Suppose I create a widget from the js side, which goes over basically without attributes to python. Then I start modifying it in js, and thus send a message about the update. I get a message back from python with the default values, which then overwrite my new values. Now I have the new values in python, but the default values in js.

Here's another idea - just delete the default value altogether for layout and style on the js side, and make sure the js code can deal with it. It should be created in the python side and automatically synced back.

**Comment by jasongrout** [comment]
(i.e., make sure the views can deal with those two values being undefined)

**Comment by jasongrout** [comment]
@maartenbreddels - can you check to see if my latest commit here also solves the problem? This way, the state messages still follow the spec (which doesn't allow for an empty dictionary).

**Comment by jasongrout** [comment]
I was trying to reproduce your error, and I was getting confused that I was not seeing the error message. Then I happened to find it in the websocket messages, even though it wasn't displaying. But then I realized that of course it wouldn't display - the callbacks are not set for that `new_widget` sync message - in fact, where should it display? Typically new_widget is called from a model, so there is no clear place to display.

It just reminded me yet again that we should have a clear notebook-wide display for messages that don't find a home, especially error messages.

**Pull request merged**
