### PR TITLE
allow for no crossorigin tag

### PR DESCRIPTION
**Pull request by maartenbreddels**
Some browers don't like this when loading from local disk.

### CODE REVIEW

**Comment by pbugnion** [comment]
I think the spaces in the interpolated template aren't quite right:

```python
import ipywidgets.embed
cors = True
use_cors = 'crossorigin="anonymous"' if cors else ' '
ipywidgets.embed.load_template.format(use_cors=use_cors, embed_url=ipywidgets.embed.DEFAULT_EMBED_SCRIPT_URL)

# => '<script src="https://unpkg.com/@jupyter-widgets/html-manager@^0.10.0/dist/embed.js"crossorigin="anonymous"></script>'
```

The `crossorigin` attribute is squashed up against `src`. I think that your definition of `use_cors` should be `' crossorigin="anonymous"' if cors else ''` (or the template should include a space).

**Comment by maartenbreddels** [comment]
Good catch!

**Comment by jasongrout** [comment]
@pbugnion - if this looks good to you, can you merge?

**Comment by pbugnion** [comment]
Looks great!

**Pull request merged**
