### PR TITLE
Fix the logic for tab selection when the children changes to select a tab when possible

### LINKED ISSUE #2818: No tab selected by default
In ipywidgets 8.0.0a0, when creating a tab widget, by default no tab is activated, which is really confusing. I think the first tab should be selected.

```python
tab_nest = widgets.Tab()
tab_nest.children = [accordion, accordion]
tab_nest.titles = ('An accordion', 'Copy of the accordion')
tab_nest
```

Screen Shot 2020-03-10 at 8 20 42 AM

### PR DESCRIPTION
**Pull request by jasongrout**
Fixes #2818

### CODE REVIEW

**Comment by jasongrout** [comment]
CC @vidartf

**Comment by vidartf** [comment]
I guess the interesting question is what happens for code like this:
```python
tab = widgets.Tab()
with tab.hold_trait_notifications():
    tab.children = [foo, bar]
    tab.selected_index = 1  # default to bar
```

**Comment by vidartf** [comment]
And the answer to that is nothing you wouldn't expect 👍

**Comment by vidartf** [comment]
I went a little fast I think, there's still this scenario:

```python
# Init in one go to avoid UI flicker:
tab = widgets.Tab(children = [foo, bar, bat], selected_index=2)

<something happens here>

# Hold notifications to avoid flicker during change:
with tab.hold_trait_notifications():
    tab.children = [foo, bar]
    tab.selected_index = 1  # Select bar
```

**Comment by vidartf** [comment]
For that case, I think `tab.selected_index == 0` ends up being the result.

**Comment by vidartf** [comment]
Of course, the work-around for that scenario is to use `tab.hold_sync` instead of `tab.hold_trait_notifications`, but there might be other scenarios where `hold_trait_notifications` is the only alternative.

**Comment by jasongrout** [comment]
> ```python
> # Init in one go to avoid UI flicker:
> tab = widgets.Tab(children = [foo, bar, bat], selected_index=2)
> 
> <something happens here>
> 
> # Hold notifications to avoid flicker during change:
> with tab.hold_trait_notifications():
>     tab.children = [foo, bar]
>     tab.selected_index = 0  # Select foo
> ```

How is that a problem? What I would think would happen is that the children gets set to a 2-element list, and the index gets set to 0, then the observe handler would run, and would see that the selected index is valid and would not change it. How is this getting set to 1?

**Comment by jasongrout** [comment]
> What I would think would happen is that the children gets set to a 2-element list, and the index gets set to 0, then the observe handler would run, and would see that the selected index is valid and would not change it. How is this getting set to 1?

Indeed, when I test it, I get selected index 0, as expected (conda-forge python 3.8.2)

**Comment by vidartf** [comment]
> What I would think would happen is that the children gets set to a 2-element list, and the index gets set to 0, then the observe handler would run, and would see that the selected index is valid and would not change it. 

You are right, my brain gets tangled up over validators.

**Comment by jasongrout** [comment]
> You are right, my brain gets tangled up over validators.

Mine too. Of course, this is *not* a validator, so it's a little easier to reason about, in that it happens after all validation. Should it be a cross validator instead, though?

**Comment by vidartf** [comment]
> Mine too. Of course, this is *not* a validator, so it's a little easier to reason about, in that it happens after all validation. Should it be a cross validator instead, though?

Possibly 🤷‍♂

**Pull request merged**
