### PR TITLE
Add support for localization to the lab extension

### PR DESCRIPTION
**Pull request by jtpio**
At the moment the "Save Widget State Automatically" command label is not translated when using JupyterLab in a different display language, in the following case in French:

image

This PR adds an optional `ITranslator` to the lab plugin to handle this.

We also use a custom `jupyterlab_widgets` domain since the extension lives outside of the core JupyterLab repo right now.

### CODE REVIEW

**Comment by jtpio** [comment]
This can be backported to 7.x.

**Comment by vidartf** [comment]
This mostly looks good to me, but to make sure I understand: If a translator wanted to add an entry for this, would they add the entry to the same language pack that JupyterLab uses? How would the versioning of our keys compare to that of JupyterLab? I.e. if we change something, how will we ensure compatibility between an old ipywidgets version and new lab and/or new ipywidgets and old lab?

**Comment by jtpio** [comment]
Since `jupyterlab_widgets` is a regular lab extension, it can follow the same process as other extensions which are currently living in https://github.com/jupyterlab/language-packs

Also this is only for the lab extension and should be independent of the main `ipywidgets` package.

I've just opened https://github.com/jupyterlab/language-packs/pull/109 to add `jupyterlab_widgets` to the list.

**Comment by fcollonval** [comment]
> but I think we are not confident that it all works on integration level just yet?

Yep for now the merge of source strings is working. But there is no information about the version from which the strings are coming. So there is no easy way to handle the lifecycle of the source strings for extensions in the JupyterLab language packs.

**Review by jasongrout — APPROVED** [review]

**Pull request merged**
