### PR TITLE
Mailmap changes

### PR DESCRIPTION
**Pull request by jasongrout**
This adds some entries to the mailmap to have more complete names, and also adds some stats for the release. This accomplishes part of #1570.

CCing some people who now have mailmap entries: @charnpreetsingh, @Ricyteach, @lzkelley, @maartenbreddels - please let me know if you would like me to remove the mailmap entry, and stick with the name specified in the commits.

CC @kikocorreoso - do you want to us to include a more complete name in the mailmap (and hence in the release notes)?

### CODE REVIEW

**Comment by kikocorreoso** [comment]
@jasongrout 'Kiko Correoso' is ok or kikocorreoso if you don't want to add further changes.

Kind regards.

**Comment by jasongrout** [comment]
> @jasongrout 'Kiko Correoso' is ok or kikocorreoso if you don't want to add further changes.

Happy to make the change. Thanks!

**Comment by lzkelley** [comment]
"Luke Zoltan Kelley" please, thanks @jasongrout

**Comment by jasongrout** [comment]
@lzkelley - thanks!

**Comment by jasongrout** [comment]
I squashed the changes into one commit, so the error isn't in the history.

**Comment by charnpreetsingh** [comment]
@jasongrout looks good to me!

**Comment by jasongrout** [comment]
@Ricyteach - if you could give positive confirmation that this change looks good to you too, that would be great.

**Comment by Ricyteach** [comment]
'Rick Teachey' please, Jason, thanks.

**Comment by jasongrout** [comment]
> 'Rick Teachey' please, Jason, thanks.

Perfect. That's what's in the current PR. Thanks again.

**Comment by Ricyteach** [comment]
Oh and yes it looks good as is, thank you.

**Pull request merged**
