### PR TITLE
Respect allow_none for Color, add FullColor

### PR DESCRIPTION
**Pull request by vidartf**
- Respects `allow_none` for `Color` trait.
- Ensure `Color.validate` raises a `TraitError` if value is not a string type, instead of `AttributeError`. E.g. `Union.validate` relies on catching `TraitError`.
- Adds trait type `FullColor` that uses the expanded HTML color definitions.

### CODE REVIEW

**Comment by vidartf** [comment]
Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value

**Comment by vidartf** [comment]
Maybe a better name than "FullColor" exists. What about `CSSColor` ?

**Comment by SylvainCorlay** [comment]
I like the validation of rgba color.

How about making it part of the base color class?

**Comment by jasongrout** [comment]
Is there a reason not to just expand the base color class with no option to restrict it to the current definition? Why not just adopt the CSS color spec completely in the base color class?

**Comment by vidartf** [comment]
If you figure this as backwards compatible enough to not wait for a major release, I'd be happy to add the changes to Color!

**Comment by jasongrout** [comment]
I think if it is strictly expanding the allowed values, it's okay to put in a minor release.

**Comment by vidartf** [comment]
Now expands the Color trait!

**Comment by maartenbreddels** [comment]
awesome work, looking good!

**Comment by SylvainCorlay** [comment]
As per discussion with @jasongrout we wanting on @jasongrout to make a patch release for jupyterlab 0.35 before merging this.

**Comment by vidartf** [comment]
@jasongrout I've lost track here. Is the relevant patch release out?

**Comment by jasongrout** [comment]
There are some patch releases out. Can you remind me why we were waiting for a jlab release for this?

**Comment by vidartf** [comment]
> Can you remind me why we were waiting for a jlab release for this?

Not really. @SylvainCorlay / @maartenbreddels do either of you remember?

**Comment by SylvainCorlay** [comment]
Sounds good to me!

**Comment by vidartf** [comment]
TODO: Include HSL values in tests.

**Comment by SylvainCorlay** [comment]
@vidartf I am fine with merging this now (for the 7.5 minor release).

Is there anything that you think we should add?

**Comment by vidartf** [comment]
@SylvainCorlay I added some simple HSL(A) tests (the original ones I wrote got lost in the previous refactor), so now I am happy.

**Comment by SylvainCorlay** [comment]
:tada:

**Comment by SylvainCorlay** [comment]
Thanks @vidartf this is going to be super useful!

**Pull request merged**
