### PR TITLE
Set value=null on DatePicker on Invalid Dates when it lost focus

### LINKED ISSUE #1895: DatePicker on Invalid Dates
When a DatePicker has an invalid value it is highlighted in orange as expected. The widget.value though is the last valid value which seems strange since there is a mismatch in the UI when something goes to process this.

Example:
```
import ipywidgets
def print_value(v):
    print(v)
w = ipywidgets.DatePicker()
w.observe(print_value, 'value')
w
```
Change the date from 01/31/2017 and keep pushing up on the first value as that you get 02/31/2017. `w.value` is `2017-01-31` still although this is not what the UI says.

Starting:
image
Ending:
image

 I would have expected it to say None as it does when it was blank when first created.

### PR DESCRIPTION
**Pull request by xmnlab**
Resolves #1895

### CODE REVIEW

**Comment by xmnlab** [comment]
hey everyone, I am trying to trigger a function when the object lost the focus, but it seems is doesn't work. 

any thoughts?

**Comment by saulshanabrook** [comment]
@xmnlab You could try adding an event listener to the `focusout` event maybe? https://developer.mozilla.org/en-US/docs/Web/API/Element/focusout_event

**Comment by xmnlab** [comment]
hey @saulshanabrook thanks! I will try that! thanks!

**Comment by xmnlab** [comment]
@saulshanabrook it seems it worked. thanks!

**Comment by xmnlab** [comment]
it is done for review.

**Comment by xmnlab** [comment]
thanks @gnestor !

could it be merged?

**Comment by gnestor** [comment]
Yes, I don't have merge rights but I approve 👍

**Comment by xmnlab** [comment]
thanks @gnestor ! :)

**Comment by xmnlab** [comment]
hey everyone, any feedback about this PR? could it be merged?

**Comment by gnestor** [comment]
@jasongrout Would you remind reviewing?

**Comment by jasongrout** [comment]
Sure, though I may not be able to in the near future. I plan to make a pass through all ipywidgets open PRs before the next ipywidgets release.

**Comment by SylvainCorlay** [comment]
Thanks for looking into this @xmnlab!

**Comment by xmnlab** [comment]
thank you all @SylvainCorlay @gnestor @jasongrout @saulshanabrook ! :)

**Pull request merged**
