### PR TITLE
WIP Make JupyterLab top-level widgets draggable

### PR DESCRIPTION
**Pull request by jasongrout**
The idea here is to make it so that it is easy to drag widgets into their own jupyterlab tab.

WIP - don't merge yet.

### CODE REVIEW

**Comment by jasongrout** [comment]
Currently, the mirrored jupyter widget does not correctly set itself as the main area current widget when it is focused. I'm investigating how to do this.

@blink1073 - any hints about how to set a widget as the dock panel currentWidget? For some reason, it seems that my new widget from the drop does not have the focus/blur handlers that seem to be on other things setting them as the dock current widgets.

**Comment by blink1073** [comment]
A dropped widget is [activated](https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/dockpanel.ts#L590) by the dock panel, and you've defined an `onActivateRequest` that ensures focus on the panel, is `onActivateRequest` not getting called on your `FocusPanel`?

**Comment by jasongrout** [comment]
onActivateRequest is getting called just fine.

What seems to be missing is that the widget is not getting added to the shell's _tracker (as happens, for example, in https://github.com/jupyterlab/jupyterlab/blob/9f5f0ac2a4620e7e8b4432ed311566d8b547e0ae/packages/application/src/shell.ts#L372 for the right-click cell mirroring). I suppose it's not getting added to the shell's `_tracker` because the drop action is an action at the phosphor dockpanel level (i.e., it doesn't know about the shell's tracker), not the application shell level.

Should the application shell override the drop event in the phosphor dockpanel to also add the new widget to the shell focus tracker?

**Comment by jasongrout** [comment]
The reason dragging from the file listing works is that the drop callback at https://github.com/jupyterlab/jupyterlab/blob/9f5f0ac2a4620e7e8b4432ed311566d8b547e0ae/packages/filebrowser/src/listing.ts#L1159 invokes `DocumentManager.open`, calling `DocumentManager._createOrOpenDocument`, which calls the opener at https://github.com/jupyterlab/jupyterlab/blob/9f5f0ac2a4620e7e8b4432ed311566d8b547e0ae/packages/docmanager-extension/src/index.ts#L89, which adds it to the main area using `addToMainArea` (which then registers the widget with the application shell focus tracker).

From this chain, it appears that a drop callback must add a widget to the main area using the shell `addToMainArea`? That seems awkward - it's probably better to have the shell's main area dockpanel's drop overridden to add the new widget to the focus tracker if it's not already there?

**Comment by blink1073** [comment]
Ha, originally the dock layout *had* a focus tracker.  Yes, I think we need to subclass `DockLayout` to add the linkage.

**Comment by jasongrout** [comment]
I made a PR to JupyterLab for adding dock children to the focus tracker: https://github.com/jupyterlab/jupyterlab/pull/3310

**Comment by jasongrout** [comment]
We now have output mirroring in jlab, which I think solves this in a different way, so I'll close this.

**Pull request closed without merging**
