### PR TITLE
Port 7.x changes to master

### LINKED ISSUE #3085: Port 7.x branch changes to master
When the 8.0 release stalled, we continued to work on the 7.x branch and release minor releases of 7.x. Consequently, there are a number of changes in the 7.x branch that should be ported to master. This issue tracks that work.

## PRs in 7.x not on master

This is a checklist of PRs merged, with the oldest at the top.

% git log master..7.x --merges --oneline | tail -r
- [x] 4b1dff6e Merge pull request #2781 from jasongrout/w7jlab2
- [x] 0f75c9fe Merge pull request #2793 from jasongrout/fontawesome: ported in #2816
- [x] c138c0f9 Merge pull request #2803 from jasongrout/jlab2: not necessary
- [x] 476cb915 Merge pull request #2804 from jasongrout/fontcolor: this is a backport of #2801
- [ ] c38ed09e Merge pull request #2973 from jasongrout/jlab3
- [ ] bd3b2e91 Merge pull request #2974 from jasongrout/release
- [ ] a6ebd34e Merge pull request #2990 from jasongrout/packaging
- [ ] 019256d5 Merge pull request #2991 from jasongrout/packaging
- [ ] 567108ba Merge pull request #2992 from jasongrout/upjlab
- [ ] 5754418e Merge pull request #2993 from jasongrout/license
- [ ] 5bb6573f Merge pull request #2995 from martinRenou/remove_jlab_dependency
- [ ] 24fe9e6e Merge pull request #3044 from jasongrout/jlab3
- [ ] f52839d4 Merge pull request #3008 from martinRenou/jupyterlab_widgets_dependency
- [ ] d6890851 Merge pull request #3045 from jasongrout/jlab3-2
- [ ] 249a7cc0 Merge pull request #3046 from jasongrout/ch2
- [ ] c25d3cc6 Merge pull request #3047 from jasongrout/updatewidget
- [ ] e7fa45cb Merge pull request #3050 from jasongrout/py2
- [ ] e15debb8 Merge pull request #3051 from jasongrout/update
- [x] a4bd5dfc Merge pull request #3014 from ianhi/7.x: see https://github.com/jupyter-widgets/ipywidgets/issues/3085#issuecomment-772929911
- [ ] 4e94892c Merge pull request #3059 from patviafore-canonical/7.x

I also noticed that commit 32d2a7b758b12c631b3356fb0c7d50f8d4646a53 was on 7.x.

### PR DESCRIPTION
**Pull request by jasongrout**
This merges 7.x into master to pick up changes since we branched 7.x.

Fixes #3085 

The basic strategy here was to do a `git merge 7.x` on master, then fix the conflicts with these ideas:
* bump any internal javascript alpha version numbers to the next highest major version, to account for the major version release done on the 7.x branch
* ignore whitespace changes, then run lint at the very end to do formatting cleanups
* copy over the existing jupyterlab manager ts files from master over the 7.x jupyterlab_widgets package, after making sure that relevant changes from 7.x on those files were already incorporated into master (see the todo item below for some things I noticed doing this)

## Checklist

- [x] Make sure all of the changes to the jlab manager `manager.ts` file from the 7.x branch make it into the master branch: https://github.com/jupyter-widgets/ipywidgets/compare/fdd710994afb9d4df30b59fab6bead2f7358e2fa...7.x#diff-fcef124ae167cb55c01a19fcf5edc6c00f4c49cbb4b56386f8acb3b434aaa386
  - Most of these changes were actually [backported](https://github.com/jupyter-widgets/ipywidgets/commit/a30e7dd1947a64520ddeb18233729831299d1b06) from #2654, which was merged into master
  - There may be more to do with how `this._kernel` works, like making sure it is actually set when the session context changes the kernel, but perhaps on another PR. This was written in https://github.com/jupyter-widgets/ipywidgets/commit/9d999d7b267ade8037b821ce356868a3ce205bd8, fyi. I've made https://github.com/jupyter-widgets/ipywidgets/issues/3088 to examine a few items to check into later.
- [x] Update https://github.com/jupyter-widgets/ipywidgets/pull/3086/files#diff-c0c3f9fac78e3426a2d3076dc6f327c613b69178c236bf8b7c478f59aac774d9 (for example, replace jqueryui license with noui slider license)

### CODE REVIEW

**Comment by jasongrout** [comment]
I think this is ready for review. I used `dev-install.sh` to install into a fresh environment and ran most of the doc example notebooks in JupyterLab, and everything looked fine to me.

Once it is reviewed and merged, I can release another 8.0 alpha.

CC @SylvainCorlay

**Comment by ianhi** [comment]
Just tried this out. Everything except for the Lorenz example worked great. I'm not sure if that's an issue with the forward port, or with master though, investigating.

image

**Review by ianhi — APPROVED** [review]
The failure above is unrelated - see https://github.com/jupyter-widgets/ipywidgets/issues/3102


I didn't read over all the code here but I tried it out and didn't run into any issues. I also checked and ipympl will run on jlab3 without issue when using this PR so custom widgets may not have so rough of a time :tada:

**Comment by jasongrout** [comment]
Thanks Ian!

I'll leave this open until tomorrow in case @SylvainCorlay or @vidartf wants to look at the code too.

**Comment by davidbrochart** [comment]
ipyleaflet works fine in jlab3 with this PR too.

**Comment by vidartf** [comment]
I tried creating a few branches to see if there were any history problems, but could not find any. I guess the only point of note is that the history of a few files will be a bit "back and forth" due to the cleanup commits, but I guess that should be ok.

**Comment by marimeireles** [comment]
Hi @jasongrout, I'm faar from being an expert in ipywidgets, but @SylvainCorlay asked me to check this PR. So, I'll give it a try and run some tests to see if I find something obvs wrong. I'll start now, I can ping you once I'm done.
Maybe @davidbrochart is also taking a look on this?

**Comment by marimeireles** [comment]
Oops, sorry, had an old page loaded here.

**Comment by vidartf** [comment]
Hmm. Inspecting the git history of a branch where this is merged into master using a merge-commit, I see one concerning item: This PR will cause tagged commits to be interleaved in the master branch. I'm also seeing a pretty complicated history-tree when using gitk. As such, I'm wondering if this should be merge back into master as a squash commit ? That will make it a little more tricky to navigate the history using git blame though ...

**Comment by vidartf** [comment]
> This PR will cause tagged commits to be interleaved in the master branch.

Actually, no, it will only be interleaved in a chronologically sorted history view.

>I'm also seeing a pretty complicated history-tree when using gitk.

This might be a good thing, not sure. My git skills aren't up to par.

**Comment by jasongrout** [comment]
@vidartf - I think on the whole it is good to have the merged 7.x commits as ancestors of master. That will help in, for example, the milestone check script over at #3091 to understand which commits are in 8.x but not in 7.x, etc. It also reflects in the history the actual process of merging in the changes

**Comment by jasongrout** [comment]
>  I'll start now, I can ping you once I'm done.

@marimeireles - great! I'm ready to merge this (or have someone else merge it). I plan to release an 8.0 alpha after merging this so we can have a clean base to test and merge new things into.

**Comment by marimeireles** [comment]
Hey @jasongrout I tested with ipycytoscape and a few other smaller things. Everything worked for me :)

**Comment by jasongrout** [comment]
@marimeireles - thanks!

@willingc - this is merged now. I'm planning to make another 8.0 alpha release later this morning or early afternoon. Please let me know if you want me to hold off for one of the docs PRs you've been blocked on.

**Pull request merged**
