### PR TITLE
Updated version compatibility for JupyterLab 0.32

### PR DESCRIPTION
**Pull request by jest**

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks! I notice that your username is `=?UTF-8?q?Przemek=20Weso=C5=82ek?= <jest@go.art.pl>`. Does that look right? Would you like to fix it using https://help.github.com/articles/setting-your-username-in-git/ and rebase your commit?

**Comment by jest** [comment]
Well, I simply edited the file via GitHub web interface, so there's no use in setting my CLI. :)

It's OK.

**Comment by jasongrout** [comment]
In that case, you might go to https://github.com/settings/profile and make sure the name there is correct, if you'd like.

We use real names (if the committer is okay with it) for our release notes, so I typically try to help commits have real names (again, if the committer is okay with it). I'm happy to resubmit this commit with your real name if you're okay with it and let us know what you'd like to put in for a real name. If not, would it be all right with you to change the 'name' part of the commit to your github user name?

**Comment by jasongrout** [comment]
(by the way, just FYI, I saw what this commit thinks is your name by going to the `.patch` version of the commit: https://github.com/jupyter-widgets/ipywidgets/commit/4995ae1ac9bd5296541924dad3dd9862027726aa.patch

**Comment by jest** [comment]
But it really is OK. What you see is Polish letter "Ł" (https://en.wikipedia.org/wiki/%C5%81) encoded in MIME header using "Q encoding" (https://www.rfc-editor.org/rfc/rfc2047.txt). It's fine in the repo:

```
$ git show --raw 4995ae1ac9bd5296541924dad3dd9862027726aa 
commit 4995ae1ac9bd5296541924dad3dd9862027726aa
Author: Przemek Wesołek <jest@go.art.pl>
Date:   Wed Apr 18 11:10:10 2018 +0200

    Updated version compatibility for JupyterLab 0.32

:100644 100644 c9286f5c 0dd336a8 M      packages/jupyterlab-manager/README.md
```

**Comment by jasongrout** [comment]
Ah, nice! Okay, thanks! I didn't realize the github `.patch` would give different results than the git command line.

**Pull request merged**
