### PR TITLE
Add Combobox to docs

### PR DESCRIPTION
**Pull request by mlucool**
Fixes: #2573

### CODE REVIEW

**Comment by mlucool** [comment]
@SylvainCorlay how are you stripping the output etc. from notebooks? I didn't see the command in the developer docs

**Comment by jasongrout** [comment]
I think I used https://github.com/kynan/nbstripout.

**Comment by jasongrout** [comment]
(Would you mind adding a section to the developer docs about this, where you would have looked for it?)

**Comment by mlucool** [comment]
@jasongrout fixed and added. Thanks!

**Comment by jasongrout** [comment]
Thanks!

**Pull request merged**
