### PR TITLE
adding option to rename interact button 1870

### PR DESCRIPTION
**Pull request by dharmaquark**
code change for https://github.com/jupyter-widgets/ipywidgets/issues/1870

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@dharmaquark it seems that you have not configured your local git installation so that the commit is not associated with your GitHub account.

For your GitHub account to be credited with this commit you can either

 - add the email associated with this commit to your GitHub account
 - re-do this commit after you change changed your git configuration to correspond to the github email.

**Comment by jasongrout** [comment]
@dharmaquark - we can work together today to get the right email associated with the commit. Good catch @SylvainCorlay - thanks!

**Comment by dharmaquark** [comment]
thanks! I've added my work email to my personal GitHub account- I think this should fix the issue? If not, I can work with Jason offline to fix my configuration!

**Comment by SylvainCorlay** [comment]
This looks good to me. I approve the PR!

**Comment by jasongrout** [comment]
Thanks! Sorry for the delay in merging this.

**Comment by wernight** [comment]
interact.options aren't well documented. Seems like `interact_manual` should be updated to support this.

**Comment by davidboles** [comment]
I would love to find an example of this in action - I can't seem to get it to work. For example, all of the commented-out attempts below fail, either because it isn't valid Python or the button remains labelled "Run Interact".

```
#@widgets.interact_manual.option(manual_name='Make It So')(color=['blue', 'red', 'green'], lw=(1., 10.))
#@widgets.interact_manual(color=['blue', 'red', 'green'], lw=(1., 10.)).options(manual_name='Make It So')
def plot(freq=1., color='blue', lw=2, grid=True):
    t = np.linspace(-1., +1., 1000)
    fig, ax = plt.subplots(1, 1, figsize=(8, 6))
    ax.plot(t, np.sin(2 * np.pi * freq * t), lw=lw, color=color)
    ax.grid(grid)
    
#w = widgets.interact_manual(plot, color=['blue', 'red', 'green'], lw=(1., 10.)).options(manual=True, manual_name='Make It So')
#w = widgets.interact_manual(plot, color=['blue', 'red', 'green'], lw=(1., 10.), options={'manual_name': 'Make It So'})
#w = widgets.interact_manual(plot, color=['blue', 'red', 'green'], lw=(1., 10.), manual_name='Make It So')

```

I think we'd benefit from having a simple working example.

**Comment by jasongrout** [comment]
Here is one way. I think it still could probably use another iteration making it easier:

```python
from ipywidgets import interact

interact_calc=interact.options(manual=True, manual_name="Calculate")

@interact_calc(x=(0,10))
def f(x):
    print(x)
```
You're right - this should be in the docs.

**Comment by jasongrout** [comment]
You could also do:
```python
interact_calc=interact_manual.options(manual_name="Calculate")
```

**Pull request merged**
