### PR TITLE
Fix npm install by building the output widget on install.

### PR DESCRIPTION
**Pull request by jasongrout**

### CODE REVIEW

**Comment by blink1073** [comment]
I think this should be [prepare](https://docs.npmjs.com/misc/scripts#deprecation-note).

**Comment by jasongrout** [comment]
Actually, we'll just take a cue from jlab and delete the prepublish/prepare steps across the board.

**Comment by jasongrout** [comment]
I'll iterate on cleaning up the package.json files in another PR.

**Comment by jasongrout** [comment]
> I think this should be prepare.

It looks like lerna doesn't support prepare yet? https://github.com/lerna/lerna/pull/499

**Comment by blink1073** [comment]
Shucks.

**Pull request merged**
