### PR TITLE
Fix DeprecationWarning in Python 3.7

### PR DESCRIPTION
**Pull request by Juanlu001**
Fix `DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`.

### CODE REVIEW

**Comment by Juanlu001** [comment]
Failures are related to pip not upgrading dependencies when it should (or we'd want it to), I think.

**Comment by vidartf** [comment]
I re-ran the failed tests, and the current failure seems significant. `collections.abc` are not present on Python 2.7. I say we should keep this PR open until the point where Python 2 support is dropped. Or, if we want this before, this PR should include a `try`/`except ImportError` clause.

**Comment by Juanlu001** [comment]
Thanks! True, I forgot about Python 2. What's the roadmap to drop it?

**Comment by vidartf** [comment]
I'm not sure if there is a specific plan, but unless we decide to drop it early, I would say the upper bound is when [Python stops supporting it](https://pythonclock.org/). If nothing else, there are many other projects that will stop supporting it at the same time, making it a coordinated push for those still on Python 2 to make the jump.

**Comment by jasongrout** [comment]
> What's the roadmap to drop it?

I'd like to drop python 2 with our next major release. We don't have a roadmap/timeline for that, though.

**Comment by jasongrout** [comment]
@SylvainCorlay, @Juanlu001 - I fixed to work on python 2 and 3.

**Comment by Juanlu001** [comment]
Thanks @jasongrout!

**Pull request merged**
