### PR TITLE
tslint for examples and packages/base

### PR DESCRIPTION
**Pull request by cnishina**

### CODE REVIEW

**Comment by pbugnion** [comment]
This looks great! Thanks for taking the time to do this.

Is there any reason we shouldn't use the same [linting rules](https://github.com/jupyterlab/jupyterlab/blob/master/tslint.json) as JupyterLab? Since many developers work on both widgets and JupyterLab, minimising the cost of switching between the two seems like a good thing.

**Comment by cnishina** [comment]
Good point. Yeah let's use the same.

**Comment by cnishina** [comment]
@pbugnion i've been changing the spacing from 4 to 2. Maybe I'm used to a [2 space indentation](https://google.github.io/styleguide/jsguide.html#formatting-block-indentation). Anyway, let me know if you want to maintain 4.

**Comment by cnishina** [comment]
Looking through some of the jupyter project indentation, they are using a 2 space indentation. See: https://github.com/jupyterlab/jupyterlab/blob/master/examples/console/src/index.ts

**Comment by jasongrout** [comment]
I wanted to change spacing to 2 spaces all at once in a quick-to-merge PR with no other outstanding PRs, since it's such a disruptive change.

I have one PR for dependencies that may conflict with an everywhere 2-space indentation change. @mwcraig is also working on a PR.

**Comment by mwcraig** [comment]
I'm ok with rebasing if I need to.

**Comment by cnishina** [comment]
@mwcraig, @jasongrout 

I am also flexible on this / do not want to hold back progress / prevent PRs from being merged / be the blocker. We could chunk it into multiple commits. I could also rebase with incoming changes. 👍

Here is my proposal of how to get some of these changes in. tslint PRs for:

* examples/ and packages/base/
* packages/controls/ and packages/html-manager/
* packages/jupyterlab-manager/ and packages/output/
* other files I probably missed in this list
* add linting checks on travis or in a pretest step

If this looks good, I'll update the issue to keep track of this.

**Comment by cnishina** [comment]
@pbugnion Could you review and let me know ^^^

**Comment by pbugnion** [comment]
I think the linting looks great! 

In terms of avoiding merge conflicts, the other complex PRs that are in progress are:

 - PR #1727, which touches exclusively `controls`
 - PR #1739, which mostly touches `jupyterlab-manager`.

Am I missing PRs? @jasongrout will have a better understanding of the work that is currently in progress.

I like your suggestion of breaking the update into chunks to avoid merge conflicts. I would just re-order the chunks to avoid touching the parts of the code mentioned above.

**Comment by pbugnion** [comment]
I'm OK with merging this, but since it's a big change, I would rather have Jason OK it as well.

**Comment by cnishina** [comment]
Yup. `lint` makes sense...I will make the update.

**Comment by cnishina** [comment]
Broken...

**Comment by jasongrout** [comment]
@cnishina - thanks *very* much for the work on this. We've been hoping to clean up the codebase for a while, and we really appreciate your efforts in this.

I've been trying to merge outstanding PRs and release so that we are in a clean state in the repo regarding outstanding work.

How are you making these changes? Are you running tslint and then modifying the code by hand?

**Comment by jasongrout** [comment]
To follow up, @cnishina decided to break this and other PRs into smaller, more focused, and more reviewable pieces.

Again, thanks *very* much for tackling this!

**Pull request closed without merging**
